from a2qt.QtWidgets import QHBoxLayout, QLabel, QPushButton, QVBoxLayout


class Ui_A2InputDialog:
    main_layout: QVBoxLayout = ...
    label: QLabel = ...
    horizontalLayout: QHBoxLayout = ...
    a2ok_button: QPushButton = ...
    a2cancel_button: QPushButton = ...
    def setupUi(self, A2InputDialog): ...
