import a2ui
import a2modsource
from a2qt import QtWidgets, QtCore

class A2ModuleView(QtWidgets.QWidget):
    mod_source: a2modsource.ModSource
    okayed: QtCore.Signal
    reload_requested: QtCore.Signal

    def __init__(self, parent: a2ui.A2Window) -> None: ...
    def draw_mod(self): ...
    def get_cfg_copy(self) -> list: ...
    def setup_ui(self) -> None: ...