#include modules\cryTweaks\sandboxSaveReminder.ahk
#include modules\cryTweaks\toggleEnable.ahk
#include modules\cryTweaks\reloadScript.ahk
#include modules\cryTweaks\copyPasteXYZ.ahk
#include modules\cryTweaks\sandBoxCloseWindows.ahk
#include modules\cryTweaks\timeScrub.ahk
#include modules\cryTweaks\setWindowRes.ahk
#include modules\cryTweaks\setMoveSpeed.ahk
#include modules\cryTweaks\sandboxBrowserBackspace.ahk
#include modules\communicatorTweaks\switchEnter.ahk
#include modules\communicatorTweaks\enableUpDown.ahk
#include modules\codeTools\mel2py.ahk
#include modules\codeTools\commandLinePaste.ahk
#include modules\winr\winr.ahk
#include modules\winTools\color.ahk
#include modules\winTools\getWinfo.ahk
#include modules\skypeKeys\skypeSnapshotKey.ahk
#include modules\webTools\BBCodeMenu.ahk
#include modules\ExplorerHotkeys\ftpExplorerCopy.ahk