# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2ctrl\a2module_view.ui'
#
# Created: Wed Aug 31 23:54:18 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ModuleView(object):
    def setupUi(self, ModuleView):
        ModuleView.setObjectName("ModuleView")
        ModuleView.resize(662, 431)
        self.verticalLayout = QtGui.QVBoxLayout(ModuleView)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsHeadLayout = QtGui.QHBoxLayout()
        self.settingsHeadLayout.setSpacing(5)
        self.settingsHeadLayout.setObjectName("settingsHeadLayout")
        self.modCheck = QtGui.QCheckBox(ModuleView)
        self.modCheck.setText("")
        self.modCheck.setTristate(False)
        self.modCheck.setObjectName("modCheck")
        self.settingsHeadLayout.addWidget(self.modCheck)
        self.modName = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.modName.setFont(font)
        self.modName.setToolTip("")
        self.modName.setStatusTip("")
        self.modName.setWhatsThis("")
        self.modName.setAccessibleName("")
        self.modName.setAccessibleDescription("")
        self.modName.setText("ModName")
        self.modName.setTextFormat(QtCore.Qt.PlainText)
        self.modName.setObjectName("modName")
        self.settingsHeadLayout.addWidget(self.modName)
        self.modVersion = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.modVersion.setFont(font)
        self.modVersion.setObjectName("modVersion")
        self.settingsHeadLayout.addWidget(self.modVersion)
        self.modAuthor = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.modAuthor.setFont(font)
        self.modAuthor.setObjectName("modAuthor")
        self.settingsHeadLayout.addWidget(self.modAuthor)
        self.a2mod_view_source_label = QtGui.QLabel(ModuleView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a2mod_view_source_label.sizePolicy().hasHeightForWidth())
        self.a2mod_view_source_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.a2mod_view_source_label.setFont(font)
        self.a2mod_view_source_label.setObjectName("a2mod_view_source_label")
        self.settingsHeadLayout.addWidget(self.a2mod_view_source_label)
        self.modInfoButton = QtGui.QPushButton(ModuleView)
        self.modInfoButton.setMinimumSize(QtCore.QSize(30, 30))
        self.modInfoButton.setMaximumSize(QtCore.QSize(30, 30))
        self.modInfoButton.setObjectName("modInfoButton")
        self.settingsHeadLayout.addWidget(self.modInfoButton)
        self.settingsHeadLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.settingsHeadLayout)
        self.a2scroll_area = QtGui.QScrollArea(ModuleView)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.a2scroll_area.setFont(font)
        self.a2scroll_area.setWidgetResizable(True)
        self.a2scroll_area.setObjectName("a2scroll_area")
        self.scrollAreaContents = QtGui.QWidget()
        self.scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 660, 359))
        self.scrollAreaContents.setObjectName("scrollAreaContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.a2scroll_area.setWidget(self.scrollAreaContents)
        self.verticalLayout.addWidget(self.a2scroll_area)
        self.a2edit_okcancel_widget = QtGui.QWidget(ModuleView)
        self.a2edit_okcancel_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.a2edit_okcancel_widget.setObjectName("a2edit_okcancel_widget")
        self.a2edit_okcancel_layout = QtGui.QHBoxLayout(self.a2edit_okcancel_widget)
        self.a2edit_okcancel_layout.setSpacing(5)
        self.a2edit_okcancel_layout.setContentsMargins(6, 6, 6, 6)
        self.a2edit_okcancel_layout.setObjectName("a2edit_okcancel_layout")
        self.a2ok_button = QtGui.QPushButton(self.a2edit_okcancel_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.a2ok_button.setFont(font)
        self.a2ok_button.setObjectName("a2ok_button")
        self.a2edit_okcancel_layout.addWidget(self.a2ok_button)
        self.a2cancel_button = QtGui.QPushButton(self.a2edit_okcancel_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a2cancel_button.sizePolicy().hasHeightForWidth())
        self.a2cancel_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.a2cancel_button.setFont(font)
        self.a2cancel_button.setFlat(True)
        self.a2cancel_button.setObjectName("a2cancel_button")
        self.a2edit_okcancel_layout.addWidget(self.a2cancel_button)
        self.a2edit_okcancel_layout.setStretch(0, 3)
        self.a2edit_okcancel_layout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.a2edit_okcancel_widget)

        self.retranslateUi(ModuleView)
        QtCore.QMetaObject.connectSlotsByName(ModuleView)

    def retranslateUi(self, ModuleView):
        ModuleView.setWindowTitle(QtGui.QApplication.translate("ModuleView", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.modVersion.setText(QtGui.QApplication.translate("ModuleView", "v0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.modAuthor.setText(QtGui.QApplication.translate("ModuleView", "- Author Name", None, QtGui.QApplication.UnicodeUTF8))
        self.a2mod_view_source_label.setText(QtGui.QApplication.translate("ModuleView", "- Module Source", None, QtGui.QApplication.UnicodeUTF8))
        self.modInfoButton.setText(QtGui.QApplication.translate("ModuleView", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.a2ok_button.setText(QtGui.QApplication.translate("ModuleView", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.a2cancel_button.setText(QtGui.QApplication.translate("ModuleView", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

