# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\a2ctrl\a2module_view.ui'
#
# Created: Sun Aug 14 22:48:43 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ModuleView(object):
    def setupUi(self, ModuleView):
        ModuleView.setObjectName("ModuleView")
        ModuleView.resize(753, 703)
        self.verticalLayout = QtGui.QVBoxLayout(ModuleView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsHeadLayout = QtGui.QHBoxLayout()
        self.settingsHeadLayout.setObjectName("settingsHeadLayout")
        self.modCheck = QtGui.QCheckBox(ModuleView)
        self.modCheck.setText("")
        self.modCheck.setTristate(False)
        self.modCheck.setObjectName("modCheck")
        self.settingsHeadLayout.addWidget(self.modCheck)
        self.modName = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.modName.setFont(font)
        self.modName.setToolTip("")
        self.modName.setStatusTip("")
        self.modName.setWhatsThis("")
        self.modName.setAccessibleName("")
        self.modName.setAccessibleDescription("")
        self.modName.setText("ModName")
        self.modName.setTextFormat(QtCore.Qt.PlainText)
        self.modName.setObjectName("modName")
        self.settingsHeadLayout.addWidget(self.modName)
        self.modVersion = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.modVersion.setFont(font)
        self.modVersion.setObjectName("modVersion")
        self.settingsHeadLayout.addWidget(self.modVersion)
        self.modAuthor = QtGui.QLabel(ModuleView)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.modAuthor.setFont(font)
        self.modAuthor.setObjectName("modAuthor")
        self.settingsHeadLayout.addWidget(self.modAuthor)
        self.modInfoButton = QtGui.QPushButton(ModuleView)
        self.modInfoButton.setMinimumSize(QtCore.QSize(30, 30))
        self.modInfoButton.setMaximumSize(QtCore.QSize(30, 30))
        self.modInfoButton.setObjectName("modInfoButton")
        self.settingsHeadLayout.addWidget(self.modInfoButton)
        self.settingsHeadLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.settingsHeadLayout)
        self.scrollArea = QtGui.QScrollArea(ModuleView)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContents = QtGui.QWidget()
        self.scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 715, 549))
        self.scrollAreaContents.setObjectName("scrollAreaContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.scrollAreaContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.editOKCancelWidget = QtGui.QWidget(ModuleView)
        self.editOKCancelWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.editOKCancelWidget.setObjectName("editOKCancelWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.editOKCancelWidget)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editOKButton = QtGui.QPushButton(self.editOKCancelWidget)
        self.editOKButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editOKButton.setFont(font)
        self.editOKButton.setStyleSheet("* {background-color: #43B6FF;}")
        self.editOKButton.setObjectName("editOKButton")
        self.horizontalLayout.addWidget(self.editOKButton)
        self.editCancelButton = QtGui.QPushButton(self.editOKCancelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editCancelButton.sizePolicy().hasHeightForWidth())
        self.editCancelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editCancelButton.setFont(font)
        self.editCancelButton.setFlat(True)
        self.editCancelButton.setObjectName("editCancelButton")
        self.horizontalLayout.addWidget(self.editCancelButton)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.editOKCancelWidget)

        self.retranslateUi(ModuleView)
        QtCore.QMetaObject.connectSlotsByName(ModuleView)

    def retranslateUi(self, ModuleView):
        ModuleView.setWindowTitle(QtGui.QApplication.translate("ModuleView", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.modVersion.setText(QtGui.QApplication.translate("ModuleView", "v0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.modAuthor.setText(QtGui.QApplication.translate("ModuleView", "- Author Name", None, QtGui.QApplication.UnicodeUTF8))
        self.modInfoButton.setText(QtGui.QApplication.translate("ModuleView", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.editOKButton.setText(QtGui.QApplication.translate("ModuleView", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.editCancelButton.setText(QtGui.QApplication.translate("ModuleView", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

