# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\a2ctrl\a2settings.ui'
#
# Created: Thu Mar 17 01:52:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_a2settings(object):
    def setupUi(self, a2settings):
        a2settings.setObjectName("a2settings")
        a2settings.resize(938, 1012)
        self.verticalLayout_2 = QtGui.QVBoxLayout(a2settings)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headLabel = QtGui.QLabel(a2settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.headLabel.setFont(font)
        self.headLabel.setWordWrap(True)
        self.headLabel.setObjectName("headLabel")
        self.verticalLayout_2.addWidget(self.headLabel)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 25, -1, 15)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(a2settings)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.a2hotkey = HotKey(a2settings)
        self.a2hotkey.setEnabled(True)
        self.a2hotkey.setObjectName("a2hotkey")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.a2hotkey)
        self.label_2 = QtGui.QLabel(a2settings)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(a2settings)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label = QtGui.QLabel(a2settings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_6 = QtGui.QLineEdit(a2settings)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout.addWidget(self.lineEdit_6)
        self.pushButton = QtGui.QPushButton(a2settings)
        self.pushButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.loadOnWinStart = QtGui.QCheckBox(a2settings)
        self.loadOnWinStart.setObjectName("loadOnWinStart")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.loadOnWinStart)
        self.rememberLastSel = QtGui.QCheckBox(a2settings)
        self.rememberLastSel.setObjectName("rememberLastSel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.rememberLastSel)
        self.enableDevMode = QtGui.QCheckBox(a2settings)
        self.enableDevMode.setObjectName("enableDevMode")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.enableDevMode)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.devBox = QtGui.QGroupBox(a2settings)
        self.devBox.setObjectName("devBox")
        self.formLayout_3 = QtGui.QFormLayout(self.devBox)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtGui.QLabel(self.devBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.authorName = QtGui.QLineEdit(self.devBox)
        self.authorName.setObjectName("authorName")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.authorName)
        self.label_6 = QtGui.QLabel(self.devBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.authorHomepage = QtGui.QLineEdit(self.devBox)
        self.authorHomepage.setObjectName("authorHomepage")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.authorHomepage)
        self.label_5 = QtGui.QLabel(self.devBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.codeEditor = QtGui.QLineEdit(self.devBox)
        self.codeEditor.setObjectName("codeEditor")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.codeEditor)
        self.checkBox_4 = QtGui.QCheckBox(self.devBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBox_4)
        self.label_8 = QtGui.QLabel(self.devBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.ahkExe = QtGui.QLineEdit(self.devBox)
        self.ahkExe.setObjectName("ahkExe")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.ahkExe)
        self.verticalLayout_2.addWidget(self.devBox)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(a2settings)
        QtCore.QMetaObject.connectSlotsByName(a2settings)

    def retranslateUi(self, a2settings):
        self.headLabel.setText(QtGui.QApplication.translate("a2settings", "Hello user! Welcome to a2! This is a template introduction Text. So far there is not much to say. I just wanted this to fill up more than one line properly. Voila!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("a2settings", "Open a2 Dialog:", None, QtGui.QApplication.UnicodeUTF8))
        self.a2hotkey.setText(QtGui.QApplication.translate("a2settings", "Win+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("a2settings", "Settings Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("a2settings", "Module Source:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("a2settings", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.loadOnWinStart.setText(QtGui.QApplication.translate("a2settings", "Load a2 on Windows Start", None, QtGui.QApplication.UnicodeUTF8))
        self.rememberLastSel.setText(QtGui.QApplication.translate("a2settings", "Remember last selected Module", None, QtGui.QApplication.UnicodeUTF8))
        self.enableDevMode.setText(QtGui.QApplication.translate("a2settings", "Enable a2 Dev mode", None, QtGui.QApplication.UnicodeUTF8))
        self.devBox.setTitle(QtGui.QApplication.translate("a2settings", "a2 Dev Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("a2settings", "Author Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("a2settings", "Author Homepage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("a2settings", "Autohotkey Code Editor:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("a2settings", "LogLevel:DEBUG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("a2settings", "Autohotkey Executable:", None, QtGui.QApplication.UnicodeUTF8))

from a2ctrl.hotkey import HotKey
