# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2ctrl\a2settings.ui'
#
# Created: Thu Aug 11 14:36:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_a2settings(object):
    def setupUi(self, a2settings):
        a2settings.setObjectName("a2settings")
        a2settings.resize(556, 558)
        self.verticalLayout_2 = QtGui.QVBoxLayout(a2settings)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headLabel = QtGui.QLabel(a2settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.headLabel.setFont(font)
        self.headLabel.setWordWrap(True)
        self.headLabel.setObjectName("headLabel")
        self.verticalLayout_2.addWidget(self.headLabel)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 25, -1, 15)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(a2settings)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.a2hotkey = HotKey(a2settings)
        self.a2hotkey.setEnabled(True)
        self.a2hotkey.setObjectName("a2hotkey")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.a2hotkey)
        self.loadOnWinStart = QtGui.QCheckBox(a2settings)
        self.loadOnWinStart.setObjectName("loadOnWinStart")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.loadOnWinStart)
        self.rememberLastSel = QtGui.QCheckBox(a2settings)
        self.rememberLastSel.setObjectName("rememberLastSel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.rememberLastSel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.groupBox = QtGui.QGroupBox(a2settings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.no_sources_msg = QtGui.QLabel(self.groupBox)
        self.no_sources_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.no_sources_msg.setWordWrap(True)
        self.no_sources_msg.setObjectName("no_sources_msg")
        self.verticalLayout.addWidget(self.no_sources_msg)
        self.add_source_button = QtGui.QPushButton(self.groupBox)
        self.add_source_button.setMaximumSize(QtCore.QSize(75, 16777215))
        self.add_source_button.setStyleSheet("QPushButton {background-color:#37ED95}")
        self.add_source_button.setObjectName("add_source_button")
        self.verticalLayout.addWidget(self.add_source_button)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.dev_box = QtGui.QGroupBox(a2settings)
        self.dev_box.setCheckable(True)
        self.dev_box.setObjectName("dev_box")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dev_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dev_widget = QtGui.QWidget(self.dev_box)
        self.dev_widget.setObjectName("dev_widget")
        self.formLayout_2 = QtGui.QFormLayout(self.dev_widget)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtGui.QLabel(self.dev_widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.settings_folder = QtGui.QLineEdit(self.dev_widget)
        self.settings_folder.setEnabled(False)
        self.settings_folder.setObjectName("settings_folder")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.settings_folder)
        self.label_4 = QtGui.QLabel(self.dev_widget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.author_name = QtGui.QLineEdit(self.dev_widget)
        self.author_name.setObjectName("author_name")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.author_name)
        self.label_6 = QtGui.QLabel(self.dev_widget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.author_homepage = QtGui.QLineEdit(self.dev_widget)
        self.author_homepage.setObjectName("author_homepage")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.author_homepage)
        self.label_5 = QtGui.QLabel(self.dev_widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.code_editor = PathField(self.dev_widget)
        self.code_editor.setObjectName("code_editor")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.code_editor)
        self.label_8 = QtGui.QLabel(self.dev_widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.ahk_exe = PathField(self.dev_widget)
        self.ahk_exe.setObjectName("ahk_exe")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.ahk_exe)
        self.debug_checkbox = QtGui.QCheckBox(self.dev_widget)
        self.debug_checkbox.setObjectName("debug_checkbox")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.debug_checkbox)
        self.verticalLayout_3.addWidget(self.dev_widget)
        self.verticalLayout_2.addWidget(self.dev_box)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(a2settings)
        QtCore.QMetaObject.connectSlotsByName(a2settings)

    def retranslateUi(self, a2settings):
        self.headLabel.setText(QtGui.QApplication.translate("a2settings", "Hello user! Welcome to a2! This is a template introduction Text. So far there is not much to say. I just wanted this to fill up more than one line properly. Voila!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("a2settings", "Open a2 Dialog:", None, QtGui.QApplication.UnicodeUTF8))
        self.a2hotkey.setText(QtGui.QApplication.translate("a2settings", "Win+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.loadOnWinStart.setText(QtGui.QApplication.translate("a2settings", "Load a2 on Windows Start", None, QtGui.QApplication.UnicodeUTF8))
        self.rememberLastSel.setText(QtGui.QApplication.translate("a2settings", "Remember last selected Module", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("a2settings", "Module Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.no_sources_msg.setText(QtGui.QApplication.translate("a2settings", "Currently there are no modules sources listed. Go ahead and add or create one:", None, QtGui.QApplication.UnicodeUTF8))
        self.add_source_button.setText(QtGui.QApplication.translate("a2settings", "Add Source", None, QtGui.QApplication.UnicodeUTF8))
        self.dev_box.setTitle(QtGui.QApplication.translate("a2settings", "a2 dev mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("a2settings", "Settings Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("a2settings", "Author Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("a2settings", "Author Homepage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("a2settings", "Autohotkey Code Editor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("a2settings", "Autohotkey Executable:", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_checkbox.setText(QtGui.QApplication.translate("a2settings", "LogLevel:DEBUG", None, QtGui.QApplication.UnicodeUTF8))

from a2ctrl.hotkey import HotKey
from a2ctrl.path_field import PathField
