# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\a2ctrl\number_edit.ui'
#
# Created: Sat Mar 26 14:35:43 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_number_edit(object):
    def setupUi(self, number_edit):
        number_edit.setObjectName("number_edit")
        number_edit.resize(837, 499)
        self.editLayout = QtGui.QFormLayout(number_edit)
        self.editLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.editLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.editLayout.setObjectName("editLayout")
        self.internalNameLabel = QtGui.QLabel(number_edit)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.internalNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.editLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.internalNameLabel)
        self.cfg_name = QtGui.QLineEdit(number_edit)
        self.cfg_name.setObjectName("cfg_name")
        self.editLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfg_name)
        self.displayLabelLabel = QtGui.QLabel(number_edit)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.displayLabelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.editLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.displayLabelLabel)
        self.cfg_label = QtGui.QLineEdit(number_edit)
        self.cfg_label.setObjectName("cfg_label")
        self.editLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cfg_label)
        self.label = QtGui.QLabel(number_edit)
        self.label.setObjectName("label")
        self.editLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.cfg_value = QtGui.QDoubleSpinBox(number_edit)
        self.cfg_value.setSuffix("")
        self.cfg_value.setDecimals(0)
        self.cfg_value.setSingleStep(1.0)
        self.cfg_value.setProperty("value", 0.0)
        self.cfg_value.setObjectName("cfg_value")
        self.editLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cfg_value)
        self.label_2 = QtGui.QLabel(number_edit)
        self.label_2.setObjectName("label_2")
        self.editLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cfg_min = QtGui.QDoubleSpinBox(number_edit)
        self.cfg_min.setMinimum(-16777215.0)
        self.cfg_min.setProperty("value", 0.0)
        self.cfg_min.setObjectName("cfg_min")
        self.horizontalLayout.addWidget(self.cfg_min)
        self.cfg_max = QtGui.QDoubleSpinBox(number_edit)
        self.cfg_max.setMinimum(-16777215.0)
        self.cfg_max.setMaximum(16777215.0)
        self.cfg_max.setProperty("value", 100.0)
        self.cfg_max.setObjectName("cfg_max")
        self.horizontalLayout.addWidget(self.cfg_max)
        self.editLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtGui.QLabel(number_edit)
        self.label_3.setObjectName("label_3")
        self.editLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cfg_decimals = QtGui.QSpinBox(number_edit)
        self.cfg_decimals.setProperty("value", 1)
        self.cfg_decimals.setObjectName("cfg_decimals")
        self.editLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cfg_decimals)
        self.label_4 = QtGui.QLabel(number_edit)
        self.label_4.setObjectName("label_4")
        self.editLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cfg_step_len = QtGui.QDoubleSpinBox(number_edit)
        self.cfg_step_len.setMaximum(16777215.0)
        self.cfg_step_len.setProperty("value", 1.0)
        self.cfg_step_len.setObjectName("cfg_step_len")
        self.editLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cfg_step_len)
        self.label_5 = QtGui.QLabel(number_edit)
        self.label_5.setObjectName("label_5")
        self.editLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cfg_suffix = QtGui.QLineEdit(number_edit)
        self.cfg_suffix.setObjectName("cfg_suffix")
        self.editLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cfg_suffix)
        self.cfg_slider = QtGui.QCheckBox(number_edit)
        self.cfg_slider.setObjectName("cfg_slider")
        self.editLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cfg_slider)

        self.retranslateUi(number_edit)
        QtCore.QMetaObject.connectSlotsByName(number_edit)

    def retranslateUi(self, number_edit):
        number_edit.setWindowTitle(QtGui.QApplication.translate("number_edit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.internalNameLabel.setText(QtGui.QApplication.translate("number_edit", "internal name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_name.setText(QtGui.QApplication.translate("number_edit", "extensionX_number1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabelLabel.setText(QtGui.QApplication.translate("number_edit", "string label:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_label.setText(QtGui.QApplication.translate("number_edit", "some number", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("number_edit", "default value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("number_edit", "min/max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("number_edit", "decimals:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("number_edit", "step length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("number_edit", "suffix label:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_slider.setText(QtGui.QApplication.translate("number_edit", "show slider", None, QtGui.QApplication.UnicodeUTF8))

