# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2ctrl\path_edit.ui'
#
# Created: Fri Jun 17 22:15:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_edit(object):
    def setupUi(self, edit):
        edit.setObjectName("edit")
        edit.resize(567, 354)
        self.editLayout = QtGui.QFormLayout(edit)
        self.editLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.editLayout.setContentsMargins(10, 5, 0, 5)
        self.editLayout.setObjectName("editLayout")
        self.internalNameLabel = QtGui.QLabel(edit)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.internalNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.editLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.internalNameLabel)
        self.cfg_name = QtGui.QLineEdit(edit)
        self.cfg_name.setObjectName("cfg_name")
        self.editLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfg_name)
        self.displayLabelLabel = QtGui.QLabel(edit)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.displayLabelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.editLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.displayLabelLabel)
        self.cfg_label = QtGui.QLineEdit(edit)
        self.cfg_label.setObjectName("cfg_label")
        self.editLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cfg_label)
        self.defaultPathLabel = QtGui.QLabel(edit)
        self.defaultPathLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.defaultPathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.defaultPathLabel.setObjectName("defaultPathLabel")
        self.editLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.defaultPathLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cfg_value = QtGui.QLineEdit(edit)
        self.cfg_value.setText("")
        self.cfg_value.setObjectName("cfg_value")
        self.horizontalLayout.addWidget(self.cfg_value)
        self.pushButton = QtGui.QPushButton(edit)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.editLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtGui.QLabel(edit)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.editLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cfg2_path_type = QtGui.QRadioButton(edit)
        self.cfg2_path_type.setChecked(True)
        self.cfg2_path_type.setObjectName("cfg2_path_type")
        self.horizontalLayout_2.addWidget(self.cfg2_path_type)
        self.cfg_path_type = QtGui.QRadioButton(edit)
        self.cfg_path_type.setObjectName("cfg_path_type")
        self.horizontalLayout_2.addWidget(self.cfg_path_type)
        self.cfg_save_mode = QtGui.QCheckBox(edit)
        self.cfg_save_mode.setObjectName("cfg_save_mode")
        self.horizontalLayout_2.addWidget(self.cfg_save_mode)
        self.horizontalLayout_2.setStretch(2, 1)
        self.editLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.cfg_writable = QtGui.QCheckBox(edit)
        self.cfg_writable.setObjectName("cfg_writable")
        self.editLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cfg_writable)
        self.label_4 = QtGui.QLabel(edit)
        self.label_4.setEnabled(False)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.editLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.tableWidget = QtGui.QTableWidget(edit)
        self.tableWidget.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.editLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.tableWidget)

        self.retranslateUi(edit)
        QtCore.QMetaObject.connectSlotsByName(edit)

    def retranslateUi(self, edit):
        edit.setWindowTitle(QtGui.QApplication.translate("edit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.internalNameLabel.setText(QtGui.QApplication.translate("edit", "internal name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_name.setText(QtGui.QApplication.translate("edit", "extensionX_path1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabelLabel.setText(QtGui.QApplication.translate("edit", "display label:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_label.setText(QtGui.QApplication.translate("edit", "some path bla", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPathLabel.setText(QtGui.QApplication.translate("edit", "default path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("edit", "browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("edit", "browse mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg2_path_type.setText(QtGui.QApplication.translate("edit", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_path_type.setText(QtGui.QApplication.translate("edit", "folder", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_save_mode.setText(QtGui.QApplication.translate("edit", "save mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_writable.setText(QtGui.QApplication.translate("edit", "writable field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("edit", "file types:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("edit", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("edit", "extension", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("edit", "All files", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("edit", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

