# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\eric\io\code\a2\ui\a2element\number_edit.ui',
# licensing of 'c:\Users\eric\io\code\a2\ui\a2element\number_edit.ui' applies.
#
# Created: Tue Jan 28 21:59:37 2020
#      by: pyside2-uic  running on PySide2 5.14.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_edit(object):
    def setupUi(self, edit):
        edit.setObjectName("edit")
        edit.resize(468, 234)
        self.edit_layout = QtWidgets.QFormLayout(edit)
        self.edit_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.edit_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_layout.setObjectName("edit_layout")
        self.internalNameLabel = QtWidgets.QLabel(edit)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.internalNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.edit_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.internalNameLabel)
        self.cfg_name = QtWidgets.QLineEdit(edit)
        self.cfg_name.setObjectName("cfg_name")
        self.edit_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cfg_name)
        self.displayLabelLabel = QtWidgets.QLabel(edit)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.displayLabelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.edit_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.displayLabelLabel)
        self.cfg_label = QtWidgets.QLineEdit(edit)
        self.cfg_label.setObjectName("cfg_label")
        self.edit_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cfg_label)
        self.label = QtWidgets.QLabel(edit)
        self.label.setObjectName("label")
        self.edit_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.value = QtWidgets.QDoubleSpinBox(edit)
        self.value.setSuffix("")
        self.value.setDecimals(0)
        self.value.setSingleStep(1.0)
        self.value.setProperty("value", 0.0)
        self.value.setObjectName("value")
        self.edit_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value)
        self.label_2 = QtWidgets.QLabel(edit)
        self.label_2.setObjectName("label_2")
        self.edit_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cfg_min = QtWidgets.QDoubleSpinBox(edit)
        self.cfg_min.setMinimum(-16777215.0)
        self.cfg_min.setProperty("value", 0.0)
        self.cfg_min.setObjectName("cfg_min")
        self.horizontalLayout.addWidget(self.cfg_min)
        self.cfg_max = QtWidgets.QDoubleSpinBox(edit)
        self.cfg_max.setMinimum(-16777215.0)
        self.cfg_max.setMaximum(16777215.0)
        self.cfg_max.setProperty("value", 100.0)
        self.cfg_max.setObjectName("cfg_max")
        self.horizontalLayout.addWidget(self.cfg_max)
        self.edit_layout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(edit)
        self.label_3.setObjectName("label_3")
        self.edit_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cfg_decimals = QtWidgets.QSpinBox(edit)
        self.cfg_decimals.setProperty("value", 1)
        self.cfg_decimals.setObjectName("cfg_decimals")
        self.edit_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cfg_decimals)
        self.label_4 = QtWidgets.QLabel(edit)
        self.label_4.setObjectName("label_4")
        self.edit_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cfg_step_len = QtWidgets.QDoubleSpinBox(edit)
        self.cfg_step_len.setMaximum(16777215.0)
        self.cfg_step_len.setProperty("value", 1.0)
        self.cfg_step_len.setObjectName("cfg_step_len")
        self.edit_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cfg_step_len)
        self.label_5 = QtWidgets.QLabel(edit)
        self.label_5.setObjectName("label_5")
        self.edit_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cfg_suffix = QtWidgets.QLineEdit(edit)
        self.cfg_suffix.setObjectName("cfg_suffix")
        self.edit_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cfg_suffix)
        self.cfg_slider = QtWidgets.QCheckBox(edit)
        self.cfg_slider.setObjectName("cfg_slider")
        self.edit_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cfg_slider)

        self.retranslateUi(edit)
        QtCore.QMetaObject.connectSlotsByName(edit)

    def retranslateUi(self, edit):
        edit.setWindowTitle(QtWidgets.QApplication.translate("edit", "Form", None, -1))
        self.internalNameLabel.setText(QtWidgets.QApplication.translate("edit", "internal name:", None, -1))
        self.cfg_name.setText(QtWidgets.QApplication.translate("edit", "extensionX_number1", None, -1))
        self.displayLabelLabel.setText(QtWidgets.QApplication.translate("edit", "display label:", None, -1))
        self.cfg_label.setText(QtWidgets.QApplication.translate("edit", "some number", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("edit", "default value:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("edit", "min/max:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("edit", "decimals:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("edit", "step length:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("edit", "suffix label:", None, -1))
        self.cfg_slider.setText(QtWidgets.QApplication.translate("edit", "show slider", None, -1))

