# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\keyboard\base.ui'
#
# Created: Wed Aug 30 15:10:17 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Keyboard(object):
    def setupUi(self, Keyboard):
        Keyboard.setObjectName("Keyboard")
        Keyboard.resize(1324, 315)
        self.verticalLayout = QtGui.QVBoxLayout(Keyboard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a2hotkey_label = QtGui.QLabel(Keyboard)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.a2hotkey_label.setFont(font)
        self.a2hotkey_label.setObjectName("a2hotkey_label")
        self.verticalLayout.addWidget(self.a2hotkey_label)
        self.keys_widget = QtGui.QWidget(Keyboard)
        self.keys_widget.setObjectName("keys_widget")
        self.keys_layout = QtGui.QHBoxLayout(self.keys_widget)
        self.keys_layout.setSpacing(15)
        self.keys_layout.setContentsMargins(0, 0, 0, 0)
        self.keys_layout.setContentsMargins(0, 0, 0, 0)
        self.keys_layout.setObjectName("keys_layout")
        self.main_block = QtGui.QVBoxLayout()
        self.main_block.setObjectName("main_block")
        self.f_row = QtGui.QHBoxLayout()
        self.f_row.setObjectName("f_row")
        self.esc_key = QtGui.QPushButton(self.keys_widget)
        self.esc_key.setObjectName("esc_key")
        self.f_row.addWidget(self.esc_key)
        self.main_block.addLayout(self.f_row)
        self.f_spacer = QtGui.QWidget(self.keys_widget)
        self.f_spacer.setObjectName("f_spacer")
        self.main_block.addWidget(self.f_spacer)
        self.enter_key_rows = QtGui.QHBoxLayout()
        self.enter_key_rows.setObjectName("enter_key_rows")
        self.top_letter_rows = QtGui.QVBoxLayout()
        self.top_letter_rows.setObjectName("top_letter_rows")
        self.number_row = QtGui.QHBoxLayout()
        self.number_row.setObjectName("number_row")
        self.backspace_key = QtGui.QPushButton(self.keys_widget)
        self.backspace_key.setObjectName("backspace_key")
        self.number_row.addWidget(self.backspace_key)
        self.top_letter_rows.addLayout(self.number_row)
        self.letter_row_top = QtGui.QHBoxLayout()
        self.letter_row_top.setObjectName("letter_row_top")
        self.tab_key = QtGui.QPushButton(self.keys_widget)
        self.tab_key.setObjectName("tab_key")
        self.letter_row_top.addWidget(self.tab_key)
        self.top_letter_rows.addLayout(self.letter_row_top)
        self.enter_key_rows.addLayout(self.top_letter_rows)
        self.main_block.addLayout(self.enter_key_rows)
        self.letter_row_middle = QtGui.QHBoxLayout()
        self.letter_row_middle.setObjectName("letter_row_middle")
        self.caps_lock_key = QtGui.QPushButton(self.keys_widget)
        self.caps_lock_key.setObjectName("caps_lock_key")
        self.letter_row_middle.addWidget(self.caps_lock_key)
        self.main_block.addLayout(self.letter_row_middle)
        self.letter_row_bottom = QtGui.QHBoxLayout()
        self.letter_row_bottom.setObjectName("letter_row_bottom")
        self.l_shift_key = QtGui.QPushButton(self.keys_widget)
        self.l_shift_key.setObjectName("l_shift_key")
        self.letter_row_bottom.addWidget(self.l_shift_key)
        self.r_shift_key = QtGui.QPushButton(self.keys_widget)
        self.r_shift_key.setObjectName("r_shift_key")
        self.letter_row_bottom.addWidget(self.r_shift_key)
        self.main_block.addLayout(self.letter_row_bottom)
        self.bottom_row = QtGui.QHBoxLayout()
        self.bottom_row.setObjectName("bottom_row")
        self.l_ctrl_key = QtGui.QPushButton(self.keys_widget)
        self.l_ctrl_key.setObjectName("l_ctrl_key")
        self.bottom_row.addWidget(self.l_ctrl_key)
        self.l_winl_key = QtGui.QPushButton(self.keys_widget)
        self.l_winl_key.setObjectName("l_winl_key")
        self.bottom_row.addWidget(self.l_winl_key)
        self.l_alt_key = QtGui.QPushButton(self.keys_widget)
        self.l_alt_key.setObjectName("l_alt_key")
        self.bottom_row.addWidget(self.l_alt_key)
        self.space_key = QtGui.QPushButton(self.keys_widget)
        self.space_key.setObjectName("space_key")
        self.bottom_row.addWidget(self.space_key)
        self.r_alt_key = QtGui.QPushButton(self.keys_widget)
        self.r_alt_key.setObjectName("r_alt_key")
        self.bottom_row.addWidget(self.r_alt_key)
        self.r_win_key = QtGui.QPushButton(self.keys_widget)
        self.r_win_key.setObjectName("r_win_key")
        self.bottom_row.addWidget(self.r_win_key)
        self.r_ctrl_key = QtGui.QPushButton(self.keys_widget)
        self.r_ctrl_key.setObjectName("r_ctrl_key")
        self.bottom_row.addWidget(self.r_ctrl_key)
        self.main_block.addLayout(self.bottom_row)
        self.keys_layout.addLayout(self.main_block)
        self.cursor_block = QtGui.QVBoxLayout()
        self.cursor_block.setObjectName("cursor_block")
        self.print_block = QtGui.QHBoxLayout()
        self.print_block.setObjectName("print_block")
        self.print_key = QtGui.QPushButton(self.keys_widget)
        self.print_key.setObjectName("print_key")
        self.print_block.addWidget(self.print_key)
        self.scroll_key = QtGui.QPushButton(self.keys_widget)
        self.scroll_key.setObjectName("scroll_key")
        self.print_block.addWidget(self.scroll_key)
        self.pause_key = QtGui.QPushButton(self.keys_widget)
        self.pause_key.setObjectName("pause_key")
        self.print_block.addWidget(self.pause_key)
        self.print_spacer = QtGui.QWidget(self.keys_widget)
        self.print_spacer.setObjectName("print_spacer")
        self.print_block.addWidget(self.print_spacer)
        self.cursor_block.addLayout(self.print_block)
        self.cursor_spacer = QtGui.QWidget(self.keys_widget)
        self.cursor_spacer.setObjectName("cursor_spacer")
        self.cursor_block.addWidget(self.cursor_spacer)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.up_key = QtGui.QPushButton(self.keys_widget)
        self.up_key.setObjectName("up_key")
        self.gridLayout.addWidget(self.up_key, 3, 1, 1, 1)
        self.left_key = QtGui.QPushButton(self.keys_widget)
        self.left_key.setObjectName("left_key")
        self.gridLayout.addWidget(self.left_key, 4, 0, 1, 1)
        self.ins_key = QtGui.QPushButton(self.keys_widget)
        self.ins_key.setObjectName("ins_key")
        self.gridLayout.addWidget(self.ins_key, 0, 0, 1, 1)
        self.home_key = QtGui.QPushButton(self.keys_widget)
        self.home_key.setObjectName("home_key")
        self.gridLayout.addWidget(self.home_key, 0, 1, 1, 1)
        self.pageup_key = QtGui.QPushButton(self.keys_widget)
        self.pageup_key.setObjectName("pageup_key")
        self.gridLayout.addWidget(self.pageup_key, 0, 2, 1, 1)
        self.del_key = QtGui.QPushButton(self.keys_widget)
        self.del_key.setObjectName("del_key")
        self.gridLayout.addWidget(self.del_key, 1, 0, 1, 1)
        self.end_key = QtGui.QPushButton(self.keys_widget)
        self.end_key.setObjectName("end_key")
        self.gridLayout.addWidget(self.end_key, 1, 1, 1, 1)
        self.pagedown_key = QtGui.QPushButton(self.keys_widget)
        self.pagedown_key.setObjectName("pagedown_key")
        self.gridLayout.addWidget(self.pagedown_key, 1, 2, 1, 1)
        self.right_key = QtGui.QPushButton(self.keys_widget)
        self.right_key.setObjectName("right_key")
        self.gridLayout.addWidget(self.right_key, 4, 2, 1, 1)
        self.down_key = QtGui.QPushButton(self.keys_widget)
        self.down_key.setObjectName("down_key")
        self.gridLayout.addWidget(self.down_key, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.keys_widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.cursor_block.addLayout(self.gridLayout)
        self.keys_layout.addLayout(self.cursor_block)
        self.num_block = QtGui.QVBoxLayout()
        self.num_block.setObjectName("num_block")
        self.num_spacer = QtGui.QWidget(self.keys_widget)
        self.num_spacer.setObjectName("num_spacer")
        self.num_block.addWidget(self.num_spacer)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.num_6_key = QtGui.QPushButton(self.keys_widget)
        self.num_6_key.setObjectName("num_6_key")
        self.gridLayout_2.addWidget(self.num_6_key, 2, 2, 1, 1)
        self.num_5_key = QtGui.QPushButton(self.keys_widget)
        self.num_5_key.setObjectName("num_5_key")
        self.gridLayout_2.addWidget(self.num_5_key, 2, 1, 1, 1)
        self.num_dot_key = QtGui.QPushButton(self.keys_widget)
        self.num_dot_key.setObjectName("num_dot_key")
        self.gridLayout_2.addWidget(self.num_dot_key, 4, 2, 1, 1)
        self.num_3_key = QtGui.QPushButton(self.keys_widget)
        self.num_3_key.setObjectName("num_3_key")
        self.gridLayout_2.addWidget(self.num_3_key, 3, 2, 1, 1)
        self.num_7_key = QtGui.QPushButton(self.keys_widget)
        self.num_7_key.setObjectName("num_7_key")
        self.gridLayout_2.addWidget(self.num_7_key, 1, 0, 1, 1)
        self.num_2_key = QtGui.QPushButton(self.keys_widget)
        self.num_2_key.setObjectName("num_2_key")
        self.gridLayout_2.addWidget(self.num_2_key, 3, 1, 1, 1)
        self.num_8_key = QtGui.QPushButton(self.keys_widget)
        self.num_8_key.setObjectName("num_8_key")
        self.gridLayout_2.addWidget(self.num_8_key, 1, 1, 1, 1)
        self.num_9_key = QtGui.QPushButton(self.keys_widget)
        self.num_9_key.setObjectName("num_9_key")
        self.gridLayout_2.addWidget(self.num_9_key, 1, 2, 1, 1)
        self.num_1_key = QtGui.QPushButton(self.keys_widget)
        self.num_1_key.setObjectName("num_1_key")
        self.gridLayout_2.addWidget(self.num_1_key, 3, 0, 1, 1)
        self.num_4_key = QtGui.QPushButton(self.keys_widget)
        self.num_4_key.setObjectName("num_4_key")
        self.gridLayout_2.addWidget(self.num_4_key, 2, 0, 1, 1)
        self.num_slash_key = QtGui.QPushButton(self.keys_widget)
        self.num_slash_key.setObjectName("num_slash_key")
        self.gridLayout_2.addWidget(self.num_slash_key, 0, 1, 1, 1)
        self.num_lock_key = QtGui.QPushButton(self.keys_widget)
        self.num_lock_key.setObjectName("num_lock_key")
        self.gridLayout_2.addWidget(self.num_lock_key, 0, 0, 1, 1)
        self.num_asterisk_key = QtGui.QPushButton(self.keys_widget)
        self.num_asterisk_key.setObjectName("num_asterisk_key")
        self.gridLayout_2.addWidget(self.num_asterisk_key, 0, 2, 1, 1)
        self.num_plus_key = QtGui.QPushButton(self.keys_widget)
        self.num_plus_key.setObjectName("num_plus_key")
        self.gridLayout_2.addWidget(self.num_plus_key, 1, 3, 2, 1)
        self.num_enter_key = QtGui.QPushButton(self.keys_widget)
        self.num_enter_key.setObjectName("num_enter_key")
        self.gridLayout_2.addWidget(self.num_enter_key, 3, 3, 2, 1)
        self.num_minus_key = QtGui.QPushButton(self.keys_widget)
        self.num_minus_key.setObjectName("num_minus_key")
        self.gridLayout_2.addWidget(self.num_minus_key, 0, 3, 1, 1)
        self.num_0_key = QtGui.QPushButton(self.keys_widget)
        self.num_0_key.setObjectName("num_0_key")
        self.gridLayout_2.addWidget(self.num_0_key, 4, 0, 1, 2)
        self.num_block.addLayout(self.gridLayout_2)
        self.keys_layout.addLayout(self.num_block)
        self.verticalLayout.addWidget(self.keys_widget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a2ok_button = QtGui.QPushButton(Keyboard)
        self.a2ok_button.setObjectName("a2ok_button")
        self.horizontalLayout.addWidget(self.a2ok_button)
        self.a2cancel_button = QtGui.QPushButton(Keyboard)
        self.a2cancel_button.setFlat(True)
        self.a2cancel_button.setObjectName("a2cancel_button")
        self.horizontalLayout.addWidget(self.a2cancel_button)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Keyboard)
        QtCore.QMetaObject.connectSlotsByName(Keyboard)

    def retranslateUi(self, Keyboard):
        Keyboard.setWindowTitle(QtGui.QApplication.translate("Keyboard", "Hotkey Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.a2hotkey_label.setText(QtGui.QApplication.translate("Keyboard", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.esc_key.setText(QtGui.QApplication.translate("Keyboard", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.backspace_key.setText(QtGui.QApplication.translate("Keyboard", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_key.setText(QtGui.QApplication.translate("Keyboard", "Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.caps_lock_key.setText(QtGui.QApplication.translate("Keyboard", "Caps Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.l_shift_key.setText(QtGui.QApplication.translate("Keyboard", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.r_shift_key.setText(QtGui.QApplication.translate("Keyboard", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ctrl_key.setText(QtGui.QApplication.translate("Keyboard", "Ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.l_winl_key.setText(QtGui.QApplication.translate("Keyboard", "Win", None, QtGui.QApplication.UnicodeUTF8))
        self.l_alt_key.setText(QtGui.QApplication.translate("Keyboard", "Alt", None, QtGui.QApplication.UnicodeUTF8))
        self.space_key.setText(QtGui.QApplication.translate("Keyboard", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.r_alt_key.setText(QtGui.QApplication.translate("Keyboard", "Alt", None, QtGui.QApplication.UnicodeUTF8))
        self.r_win_key.setText(QtGui.QApplication.translate("Keyboard", "Win", None, QtGui.QApplication.UnicodeUTF8))
        self.r_ctrl_key.setText(QtGui.QApplication.translate("Keyboard", "Ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.print_key.setText(QtGui.QApplication.translate("Keyboard", "Print Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.scroll_key.setText(QtGui.QApplication.translate("Keyboard", "Scroll Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_key.setText(QtGui.QApplication.translate("Keyboard", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.up_key.setText(QtGui.QApplication.translate("Keyboard", "u", None, QtGui.QApplication.UnicodeUTF8))
        self.left_key.setText(QtGui.QApplication.translate("Keyboard", "l", None, QtGui.QApplication.UnicodeUTF8))
        self.ins_key.setText(QtGui.QApplication.translate("Keyboard", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.home_key.setText(QtGui.QApplication.translate("Keyboard", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.pageup_key.setText(QtGui.QApplication.translate("Keyboard", "Page\n"
"Up", None, QtGui.QApplication.UnicodeUTF8))
        self.del_key.setText(QtGui.QApplication.translate("Keyboard", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.end_key.setText(QtGui.QApplication.translate("Keyboard", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.pagedown_key.setText(QtGui.QApplication.translate("Keyboard", "Page\n"
"Down", None, QtGui.QApplication.UnicodeUTF8))
        self.right_key.setText(QtGui.QApplication.translate("Keyboard", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.down_key.setText(QtGui.QApplication.translate("Keyboard", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.num_6_key.setText(QtGui.QApplication.translate("Keyboard", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.num_5_key.setText(QtGui.QApplication.translate("Keyboard", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.num_dot_key.setText(QtGui.QApplication.translate("Keyboard", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.num_3_key.setText(QtGui.QApplication.translate("Keyboard", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.num_7_key.setText(QtGui.QApplication.translate("Keyboard", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.num_2_key.setText(QtGui.QApplication.translate("Keyboard", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.num_8_key.setText(QtGui.QApplication.translate("Keyboard", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.num_9_key.setText(QtGui.QApplication.translate("Keyboard", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.num_1_key.setText(QtGui.QApplication.translate("Keyboard", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.num_4_key.setText(QtGui.QApplication.translate("Keyboard", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.num_slash_key.setText(QtGui.QApplication.translate("Keyboard", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.num_lock_key.setText(QtGui.QApplication.translate("Keyboard", "Num\n"
"Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.num_asterisk_key.setText(QtGui.QApplication.translate("Keyboard", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.num_plus_key.setText(QtGui.QApplication.translate("Keyboard", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.num_enter_key.setText(QtGui.QApplication.translate("Keyboard", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.num_minus_key.setText(QtGui.QApplication.translate("Keyboard", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.num_0_key.setText(QtGui.QApplication.translate("Keyboard", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.a2ok_button.setText(QtGui.QApplication.translate("Keyboard", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.a2cancel_button.setText(QtGui.QApplication.translate("Keyboard", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

