# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\keyboard\cursor_block.ui'
#
# Created: Sun Jan 28 23:46:15 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CursorBlock(object):
    def setupUi(self, CursorBlock):
        CursorBlock.setObjectName("CursorBlock")
        CursorBlock.resize(595, 486)
        self.verticalLayout = QtGui.QVBoxLayout(CursorBlock)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.print_block = QtGui.QHBoxLayout()
        self.print_block.setObjectName("print_block")
        self.printscreen = QtGui.QPushButton(CursorBlock)
        self.printscreen.setText("Print\n"
"Screen")
        self.printscreen.setObjectName("printscreen")
        self.print_block.addWidget(self.printscreen)
        self.scrolllock = QtGui.QPushButton(CursorBlock)
        self.scrolllock.setText("Scroll\n"
"Lock")
        self.scrolllock.setObjectName("scrolllock")
        self.print_block.addWidget(self.scrolllock)
        self.pause = QtGui.QPushButton(CursorBlock)
        self.pause.setText("Pause")
        self.pause.setObjectName("pause")
        self.print_block.addWidget(self.pause)
        self.print_spacer = QtGui.QWidget(CursorBlock)
        self.print_spacer.setObjectName("print_spacer")
        self.print_block.addWidget(self.print_spacer)
        self.verticalLayout.addLayout(self.print_block)
        self.f_spacer = QtGui.QWidget(CursorBlock)
        self.f_spacer.setObjectName("f_spacer")
        self.verticalLayout.addWidget(self.f_spacer)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pgdn = QtGui.QPushButton(CursorBlock)
        self.pgdn.setText("Page\n"
"Down")
        self.pgdn.setObjectName("pgdn")
        self.gridLayout.addWidget(self.pgdn, 1, 2, 1, 1)
        self.right = QtGui.QPushButton(CursorBlock)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.right.setFont(font)
        self.right.setText("r")
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 3, 2, 1, 1)
        self.end = QtGui.QPushButton(CursorBlock)
        self.end.setText("End")
        self.end.setObjectName("end")
        self.gridLayout.addWidget(self.end, 1, 1, 1, 1)
        self.up = QtGui.QPushButton(CursorBlock)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.up.setFont(font)
        self.up.setText("u")
        self.up.setObjectName("up")
        self.gridLayout.addWidget(self.up, 2, 1, 1, 1)
        self.home = QtGui.QPushButton(CursorBlock)
        self.home.setText("Home")
        self.home.setObjectName("home")
        self.gridLayout.addWidget(self.home, 0, 1, 1, 1)
        self.down = QtGui.QPushButton(CursorBlock)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.down.setFont(font)
        self.down.setText("d")
        self.down.setObjectName("down")
        self.gridLayout.addWidget(self.down, 3, 1, 1, 1)
        self.left = QtGui.QPushButton(CursorBlock)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.left.setFont(font)
        self.left.setText("l")
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 3, 0, 1, 1)
        self.delete_2 = QtGui.QPushButton(CursorBlock)
        self.delete_2.setText("Del")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout.addWidget(self.delete_2, 1, 0, 1, 1)
        self.pgup = QtGui.QPushButton(CursorBlock)
        self.pgup.setText("Page\n"
"Up")
        self.pgup.setObjectName("pgup")
        self.gridLayout.addWidget(self.pgup, 0, 2, 1, 1)
        self.insert = QtGui.QPushButton(CursorBlock)
        self.insert.setText("Insert")
        self.insert.setObjectName("insert")
        self.gridLayout.addWidget(self.insert, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(CursorBlock)
        QtCore.QMetaObject.connectSlotsByName(CursorBlock)

    def retranslateUi(self, CursorBlock):
        CursorBlock.setWindowTitle(QtGui.QApplication.translate("CursorBlock", "Form", None, QtGui.QApplication.UnicodeUTF8))

