# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\a2design.ui',
# licensing of 'C:\Users\eric\io\code\a2\ui\a2widget\a2design.ui' applies.
#
# Created: Wed Jan 29 15:51:58 2020
#      by: pyside2-uic  running on PySide2 5.14.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_a2MainWindow(object):
    def setupUi(self, a2MainWindow):
        a2MainWindow.setObjectName("a2MainWindow")
        font = QtGui.QFont()
        font.setPointSize(10)
        a2MainWindow.setFont(font)
        a2MainWindow.setWindowTitle("a2")
        self.centralwidget = QtWidgets.QWidget(a2MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.module_list = A2ModuleList(self.splitter)
        self.module_list.setObjectName("module_list")
        self.module_view = A2ModuleView(self.splitter)
        self.module_view.setObjectName("module_view")
        self.verticalLayout.addWidget(self.splitter)
        a2MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(a2MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setTitle("&Help")
        self.menuHelp.setObjectName("menuHelp")
        self.menuDev = QtWidgets.QMenu(self.menubar)
        self.menuDev.setTitle("&Dev")
        self.menuDev.setObjectName("menuDev")
        self.menuRollback_Changes = QtWidgets.QMenu(self.menuDev)
        self.menuRollback_Changes.setTitle("Rollback Changes")
        self.menuRollback_Changes.setObjectName("menuRollback_Changes")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setTitle("&Main")
        self.menuMain.setObjectName("menuMain")
        self.menuModule = QtWidgets.QMenu(self.menubar)
        self.menuModule.setTitle("Module")
        self.menuModule.setObjectName("menuModule")
        a2MainWindow.setMenuBar(self.menubar)
        self.actionAbout_a2 = QtWidgets.QAction(a2MainWindow)
        self.actionAbout_a2.setText("About a2")
        self.actionAbout_a2.setObjectName("actionAbout_a2")
        self.actionEdit_module = QtWidgets.QAction(a2MainWindow)
        self.actionEdit_module.setText("Edit Module")
        self.actionEdit_module.setShortcut("Ctrl+E")
        self.actionEdit_module.setObjectName("actionEdit_module")
        self.actionDisable_all_modules = QtWidgets.QAction(a2MainWindow)
        self.actionDisable_all_modules.setText("Disable All Modules")
        self.actionDisable_all_modules.setShortcut("")
        self.actionDisable_all_modules.setObjectName("actionDisable_all_modules")
        self.actionExplore_to = QtWidgets.QAction(a2MainWindow)
        self.actionExplore_to.setText("Explore to Module ...")
        self.actionExplore_to.setShortcut("Alt+E")
        self.actionExplore_to.setObjectName("actionExplore_to")
        self.actionAbout_Autohotkey = QtWidgets.QAction(a2MainWindow)
        self.actionAbout_Autohotkey.setText("About Autohotkey")
        self.actionAbout_Autohotkey.setObjectName("actionAbout_Autohotkey")
        self.actionExplore_to_a2_dir = QtWidgets.QAction(a2MainWindow)
        self.actionExplore_to_a2_dir.setText("Explore to a2 ...")
        self.actionExplore_to_a2_dir.setShortcut("")
        self.actionExplore_to_a2_dir.setObjectName("actionExplore_to_a2_dir")
        self.actionA2_settings = QtWidgets.QAction(a2MainWindow)
        self.actionA2_settings.setText("a2 Settings")
        self.actionA2_settings.setObjectName("actionA2_settings")
        self.actionExit_a2ui = QtWidgets.QAction(a2MainWindow)
        self.actionExit_a2ui.setText("Exit a2UI")
        self.actionExit_a2ui.setObjectName("actionExit_a2ui")
        self.actionRefresh_UI = QtWidgets.QAction(a2MainWindow)
        self.actionRefresh_UI.setText("Refresh UI")
        self.actionRefresh_UI.setShortcut("F5")
        self.actionRefresh_UI.setObjectName("actionRefresh_UI")
        self.actionReport_Issue = QtWidgets.QAction(a2MainWindow)
        self.actionReport_Issue.setText("Report Issue")
        self.actionReport_Issue.setObjectName("actionReport_Issue")
        self.actionNew_Module_Dialog = QtWidgets.QAction(a2MainWindow)
        self.actionNew_Module_Dialog.setText("Create New Module")
        self.actionNew_Module_Dialog.setShortcut("Ctrl+N")
        self.actionNew_Module_Dialog.setObjectName("actionNew_Module_Dialog")
        self.actionBuild_A2_Package = QtWidgets.QAction(a2MainWindow)
        self.actionBuild_A2_Package.setText("Build A2 Package")
        self.actionBuild_A2_Package.setShortcut("")
        self.actionBuild_A2_Package.setObjectName("actionBuild_A2_Package")
        self.actionCreate_New_Element = QtWidgets.QAction(a2MainWindow)
        self.actionCreate_New_Element.setText("Create New Element")
        self.actionCreate_New_Element.setShortcut("")
        self.actionCreate_New_Element.setObjectName("actionCreate_New_Element")
        self.actionHelp_on_Module = QtWidgets.QAction(a2MainWindow)
        self.actionHelp_on_Module.setText("Help on Module")
        self.actionHelp_on_Module.setShortcut("")
        self.actionHelp_on_Module.setObjectName("actionHelp_on_Module")
        self.actionRevert_Settings = QtWidgets.QAction(a2MainWindow)
        self.actionRevert_Settings.setText("Revert Settings")
        self.actionRevert_Settings.setShortcut("")
        self.actionRevert_Settings.setObjectName("actionRevert_Settings")
        self.actionReload_a2_Runtime = QtWidgets.QAction(a2MainWindow)
        self.actionReload_a2_Runtime.setText("Reload a2 Runtime")
        self.actionReload_a2_Runtime.setShortcut("")
        self.actionReload_a2_Runtime.setObjectName("actionReload_a2_Runtime")
        self.actionUnload_a2_Runtime = QtWidgets.QAction(a2MainWindow)
        self.actionUnload_a2_Runtime.setText("Unload a2 Runtime")
        self.actionUnload_a2_Runtime.setObjectName("actionUnload_a2_Runtime")
        self.actionLoad_a2_Runtime = QtWidgets.QAction(a2MainWindow)
        self.actionLoad_a2_Runtime.setText("Load a2 Runtime")
        self.actionLoad_a2_Runtime.setObjectName("actionLoad_a2_Runtime")
        self.actionExplore_to_a2_data_dir = QtWidgets.QAction(a2MainWindow)
        self.actionExplore_to_a2_data_dir.setText("Explore to a2 data ...")
        self.actionExplore_to_a2_data_dir.setShortcut("")
        self.actionExplore_to_a2_data_dir.setObjectName("actionExplore_to_a2_data_dir")
        self.menuHelp.addAction(self.actionReport_Issue)
        self.menuHelp.addAction(self.actionAbout_a2)
        self.menuHelp.addAction(self.actionAbout_Autohotkey)
        self.menuDev.addAction(self.actionNew_Module_Dialog)
        self.menuDev.addAction(self.actionEdit_module)
        self.menuDev.addAction(self.actionExplore_to)
        self.menuDev.addAction(self.menuRollback_Changes.menuAction())
        self.menuDev.addSeparator()
        self.menuDev.addAction(self.actionDisable_all_modules)
        self.menuDev.addAction(self.actionExplore_to_a2_dir)
        self.menuDev.addAction(self.actionExplore_to_a2_data_dir)
        self.menuDev.addSeparator()
        self.menuDev.addAction(self.actionCreate_New_Element)
        self.menuDev.addAction(self.actionBuild_A2_Package)
        self.menuMain.addAction(self.actionA2_settings)
        self.menuMain.addAction(self.actionRefresh_UI)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionReload_a2_Runtime)
        self.menuMain.addAction(self.actionLoad_a2_Runtime)
        self.menuMain.addAction(self.actionUnload_a2_Runtime)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit_a2ui)
        self.menuModule.addAction(self.actionHelp_on_Module)
        self.menuModule.addAction(self.actionRevert_Settings)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuModule.menuAction())
        self.menubar.addAction(self.menuDev.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(a2MainWindow)
        QtCore.QMetaObject.connectSlotsByName(a2MainWindow)

    def retranslateUi(self, a2MainWindow):
        pass

from a2widget.a2module_view import A2ModuleView
from a2widget.a2module_list import A2ModuleList
