# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\a2design.ui'
#
# Created: Mon Aug 21 16:34:17 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_a2MainWindow(object):
    def setupUi(self, a2MainWindow):
        a2MainWindow.setObjectName("a2MainWindow")
        a2MainWindow.resize(766, 635)
        font = QtGui.QFont()
        font.setPointSize(10)
        a2MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(a2MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.module_list = A2ModuleList(self.splitter)
        self.module_list.setObjectName("module_list")
        self.module_view = A2ModuleView(self.splitter)
        self.module_view.setObjectName("module_view")
        self.verticalLayout.addWidget(self.splitter)
        a2MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(a2MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 25))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDev = QtGui.QMenu(self.menubar)
        self.menuDev.setObjectName("menuDev")
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuModule = QtGui.QMenu(self.menubar)
        self.menuModule.setObjectName("menuModule")
        a2MainWindow.setMenuBar(self.menubar)
        self.actionAbout_a2 = QtGui.QAction(a2MainWindow)
        self.actionAbout_a2.setShortcut("F1")
        self.actionAbout_a2.setObjectName("actionAbout_a2")
        self.actionEdit_module = QtGui.QAction(a2MainWindow)
        self.actionEdit_module.setObjectName("actionEdit_module")
        self.actionDisable_all_modules = QtGui.QAction(a2MainWindow)
        self.actionDisable_all_modules.setObjectName("actionDisable_all_modules")
        self.actionExplore_to = QtGui.QAction(a2MainWindow)
        self.actionExplore_to.setShortcut("Alt+E")
        self.actionExplore_to.setObjectName("actionExplore_to")
        self.actionDev_settings = QtGui.QAction(a2MainWindow)
        self.actionDev_settings.setObjectName("actionDev_settings")
        self.actionAbout_Autohotkey = QtGui.QAction(a2MainWindow)
        self.actionAbout_Autohotkey.setObjectName("actionAbout_Autohotkey")
        self.actionExplore_to_a2_dir = QtGui.QAction(a2MainWindow)
        self.actionExplore_to_a2_dir.setObjectName("actionExplore_to_a2_dir")
        self.actionTest_restorewin = QtGui.QAction(a2MainWindow)
        self.actionTest_restorewin.setObjectName("actionTest_restorewin")
        self.actionNew_module = QtGui.QAction(a2MainWindow)
        self.actionNew_module.setObjectName("actionNew_module")
        self.actionA2_settings = QtGui.QAction(a2MainWindow)
        self.actionA2_settings.setObjectName("actionA2_settings")
        self.actionExit_a2ui = QtGui.QAction(a2MainWindow)
        self.actionExit_a2ui.setObjectName("actionExit_a2ui")
        self.actionRefresh_UI = QtGui.QAction(a2MainWindow)
        self.actionRefresh_UI.setObjectName("actionRefresh_UI")
        self.actionReport_Issue = QtGui.QAction(a2MainWindow)
        self.actionReport_Issue.setObjectName("actionReport_Issue")
        self.actionNew_Module_Dialog = QtGui.QAction(a2MainWindow)
        self.actionNew_Module_Dialog.setShortcut("Ctrl+N")
        self.actionNew_Module_Dialog.setObjectName("actionNew_Module_Dialog")
        self.actionBuild_A2_Package = QtGui.QAction(a2MainWindow)
        self.actionBuild_A2_Package.setObjectName("actionBuild_A2_Package")
        self.actionCreate_New_Element = QtGui.QAction(a2MainWindow)
        self.actionCreate_New_Element.setObjectName("actionCreate_New_Element")
        self.actionHelp_on_Module = QtGui.QAction(a2MainWindow)
        self.actionHelp_on_Module.setObjectName("actionHelp_on_Module")
        self.actionRevert_Settings = QtGui.QAction(a2MainWindow)
        self.actionRevert_Settings.setObjectName("actionRevert_Settings")
        self.actionReload_a2_Runtime = QtGui.QAction(a2MainWindow)
        self.actionReload_a2_Runtime.setObjectName("actionReload_a2_Runtime")
        self.actionUnload_a2_Runtime = QtGui.QAction(a2MainWindow)
        self.actionUnload_a2_Runtime.setObjectName("actionUnload_a2_Runtime")
        self.actionLoad_a2_Runtime = QtGui.QAction(a2MainWindow)
        self.actionLoad_a2_Runtime.setObjectName("actionLoad_a2_Runtime")
        self.menuHelp.addAction(self.actionReport_Issue)
        self.menuHelp.addAction(self.actionAbout_a2)
        self.menuHelp.addAction(self.actionAbout_Autohotkey)
        self.menuDev.addAction(self.actionNew_Module_Dialog)
        self.menuDev.addAction(self.actionEdit_module)
        self.menuDev.addAction(self.actionExplore_to)
        self.menuDev.addSeparator()
        self.menuDev.addAction(self.actionDisable_all_modules)
        self.menuDev.addAction(self.actionExplore_to_a2_dir)
        self.menuDev.addSeparator()
        self.menuDev.addAction(self.actionCreate_New_Element)
        self.menuDev.addAction(self.actionBuild_A2_Package)
        self.menuMain.addAction(self.actionA2_settings)
        self.menuMain.addAction(self.actionRefresh_UI)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionReload_a2_Runtime)
        self.menuMain.addAction(self.actionLoad_a2_Runtime)
        self.menuMain.addAction(self.actionUnload_a2_Runtime)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit_a2ui)
        self.menuModule.addAction(self.actionHelp_on_Module)
        self.menuModule.addAction(self.actionRevert_Settings)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuModule.menuAction())
        self.menubar.addAction(self.menuDev.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(a2MainWindow)
        QtCore.QMetaObject.connectSlotsByName(a2MainWindow)

    def retranslateUi(self, a2MainWindow):
        a2MainWindow.setWindowTitle(QtGui.QApplication.translate("a2MainWindow", "a2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("a2MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDev.setTitle(QtGui.QApplication.translate("a2MainWindow", "&Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMain.setTitle(QtGui.QApplication.translate("a2MainWindow", "&Main", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModule.setTitle(QtGui.QApplication.translate("a2MainWindow", "Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_a2.setText(QtGui.QApplication.translate("a2MainWindow", "About a2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_module.setText(QtGui.QApplication.translate("a2MainWindow", "Edit Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisable_all_modules.setText(QtGui.QApplication.translate("a2MainWindow", "Disable All Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplore_to.setText(QtGui.QApplication.translate("a2MainWindow", "Explore to Module ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDev_settings.setText(QtGui.QApplication.translate("a2MainWindow", "Dev Settings ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Autohotkey.setText(QtGui.QApplication.translate("a2MainWindow", "About Autohotkey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplore_to_a2_dir.setText(QtGui.QApplication.translate("a2MainWindow", "Explore to a2 Dir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_restorewin.setText(QtGui.QApplication.translate("a2MainWindow", "test restoring window outside of screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_module.setText(QtGui.QApplication.translate("a2MainWindow", "New Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA2_settings.setText(QtGui.QApplication.translate("a2MainWindow", "a2 Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_a2ui.setText(QtGui.QApplication.translate("a2MainWindow", "Exit a2UI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_UI.setText(QtGui.QApplication.translate("a2MainWindow", "Refresh UI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_UI.setShortcut(QtGui.QApplication.translate("a2MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_Issue.setText(QtGui.QApplication.translate("a2MainWindow", "Report Issue", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Module_Dialog.setText(QtGui.QApplication.translate("a2MainWindow", "Create New Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild_A2_Package.setText(QtGui.QApplication.translate("a2MainWindow", "Build A2 Package", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_New_Element.setText(QtGui.QApplication.translate("a2MainWindow", "Create New Element", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_on_Module.setText(QtGui.QApplication.translate("a2MainWindow", "Help on Module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRevert_Settings.setText(QtGui.QApplication.translate("a2MainWindow", "Revert Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_a2_Runtime.setText(QtGui.QApplication.translate("a2MainWindow", "Reload a2 Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnload_a2_Runtime.setText(QtGui.QApplication.translate("a2MainWindow", "Unload a2 Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_a2_Runtime.setText(QtGui.QApplication.translate("a2MainWindow", "Load a2 Runtime", None, QtGui.QApplication.UnicodeUTF8))

from a2widget.a2module_list import A2ModuleList
from a2widget.a2module_view import A2ModuleView
