# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\a2settings_view.ui',
# licensing of 'C:\Users\eric\io\code\a2\ui\a2widget\a2settings_view.ui' applies.
#
# Created: Sun Jun 17 23:09:57 2018
#      by: pyside2-uic  running on PySide2 5.11.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_a2settings(object):
    def setupUi(self, a2settings):
        a2settings.setObjectName("a2settings")
        a2settings.resize(834, 840)
        a2settings.setWindowTitle("a2settings")
        a2settings.setStyleSheet("b")
        self.a2settings_view_layout = QtWidgets.QVBoxLayout(a2settings)
        self.a2settings_view_layout.setContentsMargins(0, 0, 0, 0)
        self.a2settings_view_layout.setObjectName("a2settings_view_layout")
        self.tabWidget = QtWidgets.QTabWidget(a2settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("Q")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.a2hotkey = A2Hotkey(self.tab_2)
        self.a2hotkey.setEnabled(True)
        self.a2hotkey.setObjectName("a2hotkey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.a2hotkey)
        self.load_on_win_start = QtWidgets.QCheckBox(self.tab_2)
        self.load_on_win_start.setObjectName("load_on_win_start")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.load_on_win_start)
        self.remember_selection = QtWidgets.QCheckBox(self.tab_2)
        self.remember_selection.setObjectName("remember_selection")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remember_selection)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(100, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.module_source_box = QtWidgets.QGroupBox(self.tab_2)
        self.module_source_box.setObjectName("module_source_box")
        self.mod_source_box_layout = QtWidgets.QVBoxLayout(self.module_source_box)
        self.mod_source_box_layout.setSpacing(10)
        self.mod_source_box_layout.setObjectName("mod_source_box_layout")
        self.mod_source_layout = QtWidgets.QVBoxLayout()
        self.mod_source_layout.setObjectName("mod_source_layout")
        self.mod_source_box_layout.addLayout(self.mod_source_layout)
        self.no_sources_msg = QtWidgets.QLabel(self.module_source_box)
        self.no_sources_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.no_sources_msg.setWordWrap(True)
        self.no_sources_msg.setObjectName("no_sources_msg")
        self.mod_source_box_layout.addWidget(self.no_sources_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a2add_button = QtWidgets.QPushButton(self.module_source_box)
        self.a2add_button.setObjectName("a2add_button")
        self.horizontalLayout.addWidget(self.a2add_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mod_source_box_layout.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.module_source_box)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ui_scale_label = QtWidgets.QLabel(self.tab)
        self.ui_scale_label.setObjectName("ui_scale_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ui_scale_label)
        self.ui_scale_slider = A2Slider(self.tab)
        self.ui_scale_slider.setDecimals(2)
        self.ui_scale_slider.setMinimum(0.3)
        self.ui_scale_slider.setMaximum(2.0)
        self.ui_scale_slider.setSingleStep(0.05)
        self.ui_scale_slider.setProperty("value", 1.0)
        self.ui_scale_slider.setObjectName("ui_scale_slider")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_scale_slider)
        self.dev_box = QtWidgets.QGroupBox(self.tab)
        self.dev_box.setCheckable(True)
        self.dev_box.setObjectName("dev_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dev_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dev_widget = QtWidgets.QWidget(self.dev_box)
        self.dev_widget.setObjectName("dev_widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dev_widget)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dev_widget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.author_name = QtWidgets.QLineEdit(self.dev_widget)
        self.author_name.setObjectName("author_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.author_name)
        self.label_6 = QtWidgets.QLabel(self.dev_widget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.author_url = QtWidgets.QLineEdit(self.dev_widget)
        self.author_url.setObjectName("author_url")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.author_url)
        self.line = QtWidgets.QFrame(self.dev_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(100, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_2 = QtWidgets.QLabel(self.dev_widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.settings_folder = QtWidgets.QLineEdit(self.dev_widget)
        self.settings_folder.setEnabled(False)
        self.settings_folder.setObjectName("settings_folder")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.settings_folder)
        self.label_7 = QtWidgets.QLabel(self.dev_widget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.module_folder = QtWidgets.QLineEdit(self.dev_widget)
        self.module_folder.setEnabled(False)
        self.module_folder.setObjectName("module_folder")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.module_folder)
        self.label_10 = QtWidgets.QLabel(self.dev_widget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.python_executable = QtWidgets.QLineEdit(self.dev_widget)
        self.python_executable.setEnabled(False)
        self.python_executable.setObjectName("python_executable")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.python_executable)
        self.label_5 = QtWidgets.QLabel(self.dev_widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.code_editor = A2PathField(self.dev_widget)
        self.code_editor.setObjectName("code_editor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.code_editor)
        self.label_8 = QtWidgets.QLabel(self.dev_widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.autohotkey = A2PathField(self.dev_widget)
        self.autohotkey.setObjectName("autohotkey")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.autohotkey)
        self.label_12 = QtWidgets.QLabel(self.dev_widget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.startup_tooltips = QtWidgets.QCheckBox(self.dev_widget)
        self.startup_tooltips.setObjectName("startup_tooltips")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.startup_tooltips)
        self.label_11 = QtWidgets.QLabel(self.dev_widget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.loglevel_debug = QtWidgets.QCheckBox(self.dev_widget)
        self.loglevel_debug.setObjectName("loglevel_debug")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.loglevel_debug)
        self.show_console = QtWidgets.QCheckBox(self.dev_widget)
        self.show_console.setObjectName("show_console")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.show_console)
        self.label_9 = QtWidgets.QLabel(self.dev_widget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.json_indent = QtWidgets.QSpinBox(self.dev_widget)
        self.json_indent.setMaximumSize(QtCore.QSize(70, 16777215))
        self.json_indent.setObjectName("json_indent")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.json_indent)
        self.verticalLayout_3.addWidget(self.dev_widget)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.dev_box)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.db_print_all_button = QtWidgets.QPushButton(self.tab_4)
        self.db_print_all_button.setObjectName("db_print_all_button")
        self.verticalLayout_5.addWidget(self.db_print_all_button)
        self.db_printout = QtWidgets.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.db_printout.setFont(font)
        self.db_printout.setReadOnly(True)
        self.db_printout.setObjectName("db_printout")
        self.verticalLayout_5.addWidget(self.db_printout)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 806, 741))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.a2license_text = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.a2license_text.setAutoFillBackground(False)
        self.a2license_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.a2license_text.setWordWrap(True)
        self.a2license_text.setOpenExternalLinks(True)
        self.a2license_text.setObjectName("a2license_text")
        self.verticalLayout_4.addWidget(self.a2license_text)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.a2settings_view_layout.addWidget(self.tabWidget)

        self.retranslateUi(a2settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(a2settings)

    def retranslateUi(self, a2settings):
        self.label_3.setText(QtWidgets.QApplication.translate("a2settings", "Open a2 Dialog:", None, -1))
        self.a2hotkey.setText(QtWidgets.QApplication.translate("a2settings", "Win+Shift+A", None, -1))
        self.load_on_win_start.setText(QtWidgets.QApplication.translate("a2settings", "Load a2 on Windows Start", None, -1))
        self.remember_selection.setText(QtWidgets.QApplication.translate("a2settings", "Remember last selected Module", None, -1))
        self.module_source_box.setTitle(QtWidgets.QApplication.translate("a2settings", "Module Sources", None, -1))
        self.no_sources_msg.setText(QtWidgets.QApplication.translate("a2settings", "Currently there are no modules sources listed.\n"
"Go ahead and add or create one:", None, -1))
        self.a2add_button.setText(QtWidgets.QApplication.translate("a2settings", "Add Source", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("a2settings", "a2 Settings", None, -1))
        self.ui_scale_label.setText(QtWidgets.QApplication.translate("a2settings", "UI Scale:", None, -1))
        self.dev_box.setTitle(QtWidgets.QApplication.translate("a2settings", "a2 dev mode", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("a2settings", "Author Name:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("a2settings", "Author Homepage:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("a2settings", "Settings Folder:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("a2settings", "Modules Folder:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("a2settings", "Python Executable:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("a2settings", "Autohotkey Code Editor:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("a2settings", "Autohotkey Executable:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("a2settings", "a2 runtime:", None, -1))
        self.startup_tooltips.setText(QtWidgets.QApplication.translate("a2settings", "Enable Startup Tooltips", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("a2settings", "Python Output:", None, -1))
        self.loglevel_debug.setText(QtWidgets.QApplication.translate("a2settings", "LogLevel:DEBUG", None, -1))
        self.show_console.setText(QtWidgets.QApplication.translate("a2settings", "Show Console", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("a2settings", "JSON Indent:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("a2settings", "Advanced", None, -1))
        self.db_print_all_button.setText(QtWidgets.QApplication.translate("a2settings", "get db digest", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("a2settings", "Database View", None, -1))
        self.a2license_text.setText(QtWidgets.QApplication.translate("a2settings", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><img src=\"res/logo_ahk.png\"/><br/><span style=\" font-weight:600;\">AutoHotkey</span> - a scripting language for desktop automation</p><p align=\"center\"><a href=\"https://autohotkey.com\"><span style=\" text-decoration: underline; color:#0000ff;\">https://autohotkey.com</span></a> - GNU GPLv2</p><p align=\"center\"><br/></p><p align=\"center\"><img src=\"res/logo_python.png\"/></p><p align=\"center\"><span style=\" font-weight:600;\">Python</span> - high-level programming language</p><p align=\"center\"><a href=\"https://www.python.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.python.org</span></a> - Python Software Foundation License - GPL compatible</p><p align=\"center\"><br/></p><p align=\"center\"><img src=\"res/logo_pyside.png\"/></p><p align=\"center\"><span style=\" font-weight:600;\">PySide2</span> - Python binding of the cross-platform GUI toolkit Qt</p><p align=\"center\"><a href=\"https://wiki.qt.io/Pyside\"><span style=\" text-decoration: underline; color:#0000ff;\">https://wiki.qt.io/Pyside</span></a> - LGPL</p><p align=\"center\"><br/></p><p align=\"center\"><img src=\"res/logo_material.png\"/></p><p align=\"center\"><span style=\" font-weight:600;\">Material Icons</span> - Material Design icons by Google</p><p align=\"center\"><a href=\"https://material.io/icons\"><span style=\" text-decoration: underline; color:#0000ff;\">https://material.io/icons</span></a> - Apache License Version 2.0</p><p align=\"center\"><br/></p><p align=\"center\">Thanks!</p><p align=\"center\">...</p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("a2settings", "Licenses", None, -1))

from a2widget.a2path_field import A2PathField
from a2widget.a2hotkey import A2Hotkey
from a2widget.a2slider import A2Slider
