# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file:
#   'a2\ui\a2widget\a2settings_advanced.ui'
# licensing of that file applies.
#
# Created: Fri Oct  2 01:54:44 2020
#      by: pyside2-uic  running on PySide2 5.15.1
#
# pylint: disable=W0201,C0103,C0111
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form:
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(839, 768)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.a2scroll_area_background = QtWidgets.QWidget()
        self.a2scroll_area_background.setGeometry(QtCore.QRect(0, 0, 815, 744))
        self.a2scroll_area_background.setObjectName("a2scroll_area_background")
        self.formLayout_3 = QtWidgets.QFormLayout(self.a2scroll_area_background)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ui_scale_label = QtWidgets.QLabel(self.a2scroll_area_background)
        self.ui_scale_label.setText("UI Scale:")
        self.ui_scale_label.setObjectName("ui_scale_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ui_scale_label)
        self.ui_scale_slider = A2Slider(self.a2scroll_area_background)
        self.ui_scale_slider.setDecimals(2)
        self.ui_scale_slider.setMinimum(0.5)
        self.ui_scale_slider.setMaximum(2.0)
        self.ui_scale_slider.setSingleStep(0.05)
        self.ui_scale_slider.setProperty("value", 1.0)
        self.ui_scale_slider.setObjectName("ui_scale_slider")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_scale_slider)
        self.hotkey_box = QtWidgets.QGroupBox(self.a2scroll_area_background)
        self.hotkey_box.setTitle("Hotkey Dialog")
        self.hotkey_box.setObjectName("hotkey_box")
        self.formLayout_4 = QtWidgets.QFormLayout(self.hotkey_box)
        self.formLayout_4.setContentsMargins(-1, 25, -1, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.hotkey_box)
        self.label_7.setText("Style:")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.hk_dialog_style = QtWidgets.QComboBox(self.hotkey_box)
        self.hk_dialog_style.setObjectName("hk_dialog_style")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hk_dialog_style)
        self.label_13 = QtWidgets.QLabel(self.hotkey_box)
        self.label_13.setText("Keyboard Layout:")
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.hk_dialog_layout = QtWidgets.QComboBox(self.hotkey_box)
        self.hk_dialog_layout.setObjectName("hk_dialog_layout")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hk_dialog_layout)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.hotkey_box)
        self.dev_box = QtWidgets.QGroupBox(self.a2scroll_area_background)
        self.dev_box.setTitle("a2 dev mode")
        self.dev_box.setCheckable(True)
        self.dev_box.setObjectName("dev_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dev_box)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dev_widget = QtWidgets.QWidget(self.dev_box)
        self.dev_widget.setAccessibleDescription("")
        self.dev_widget.setObjectName("dev_widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dev_widget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dev_widget)
        self.label_4.setText("Author Name:")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.author_name = QtWidgets.QLineEdit(self.dev_widget)
        self.author_name.setText("")
        self.author_name.setObjectName("author_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.author_name)
        self.label_6 = QtWidgets.QLabel(self.dev_widget)
        self.label_6.setText("Author Homepage:")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.author_url = QtWidgets.QLineEdit(self.dev_widget)
        self.author_url.setText("")
        self.author_url.setObjectName("author_url")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.author_url)
        self.label_5 = QtWidgets.QLabel(self.dev_widget)
        self.label_5.setText("Default Code Editor:")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.code_editor = A2PathField(self.dev_widget)
        self.code_editor.setText("")
        self.code_editor.setObjectName("code_editor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.code_editor)
        self.label_8 = QtWidgets.QLabel(self.dev_widget)
        self.label_8.setText("Autohotkey Executable:")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.autohotkey = A2PathField(self.dev_widget)
        self.autohotkey.setEnabled(False)
        self.autohotkey.setText("")
        self.autohotkey.setObjectName("autohotkey")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.autohotkey)
        self.label_12 = QtWidgets.QLabel(self.dev_widget)
        self.label_12.setEnabled(False)
        self.label_12.setText("a2 runtime:")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.startup_tooltips = QtWidgets.QCheckBox(self.dev_widget)
        self.startup_tooltips.setEnabled(False)
        self.startup_tooltips.setText("Enable Startup Tooltips")
        self.startup_tooltips.setObjectName("startup_tooltips")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.startup_tooltips)
        self.label_9 = QtWidgets.QLabel(self.dev_widget)
        self.label_9.setText("JSON Indent:")
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.json_indent = QtWidgets.QSpinBox(self.dev_widget)
        self.json_indent.setMaximumSize(QtCore.QSize(70, 16777215))
        self.json_indent.setObjectName("json_indent")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.json_indent)
        self.line = QtWidgets.QFrame(self.dev_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(100, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_2 = QtWidgets.QLabel(self.dev_widget)
        self.label_2.setText("User Data:")
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.data_folder = A2PathField(self.dev_widget)
        self.data_folder.setEnabled(False)
        self.data_folder.setText("")
        self.data_folder.setObjectName("data_folder")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.data_folder)
        self.label_10 = QtWidgets.QLabel(self.dev_widget)
        self.label_10.setText("Python Executable:")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.python_executable = A2PathField(self.dev_widget)
        self.python_executable.setEnabled(False)
        self.python_executable.setText("")
        self.python_executable.setObjectName("python_executable")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.python_executable)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_set_user_dir_standard = QtWidgets.QPushButton(self.dev_widget)
        self.button_set_user_dir_standard.setText("Set User Dir Standard ")
        self.button_set_user_dir_standard.setObjectName("button_set_user_dir_standard")
        self.horizontalLayout_4.addWidget(self.button_set_user_dir_standard)
        self.button_set_user_dir_custom = QtWidgets.QPushButton(self.dev_widget)
        self.button_set_user_dir_custom.setText("Set Override Path")
        self.button_set_user_dir_custom.setObjectName("button_set_user_dir_custom")
        self.horizontalLayout_4.addWidget(self.button_set_user_dir_custom)
        self.formLayout_2.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.portable_label = QtWidgets.QLabel(self.dev_widget)
        self.portable_label.setWordWrap(True)
        self.portable_label.setObjectName("portable_label")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.portable_label)
        self.verticalLayout_3.addWidget(self.dev_widget)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.dev_box)
        self.proxy_box = QtWidgets.QGroupBox(self.a2scroll_area_background)
        self.proxy_box.setTitle("Use a Proxy")
        self.proxy_box.setCheckable(True)
        self.proxy_box.setChecked(False)
        self.proxy_box.setObjectName("proxy_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.proxy_box)
        self.verticalLayout_4.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.proxy_http = QtWidgets.QComboBox(self.proxy_box)
        self.proxy_http.setProperty("currentText", "http://")
        self.proxy_http.setObjectName("proxy_http")
        self.proxy_http.addItem("")
        self.proxy_http.setItemText(0, "http://")
        self.proxy_http.addItem("")
        self.proxy_http.setItemText(1, "https://")
        self.horizontalLayout_2.addWidget(self.proxy_http)
        self.proxy_user = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_user.setPlaceholderText("user name")
        self.proxy_user.setObjectName("proxy_user")
        self.horizontalLayout_2.addWidget(self.proxy_user)
        self.label = QtWidgets.QLabel(self.proxy_box)
        self.label.setText(":")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.proxy_pass = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.proxy_pass.setPlaceholderText("password")
        self.proxy_pass.setObjectName("proxy_pass")
        self.horizontalLayout_2.addWidget(self.proxy_pass)
        self.label_14 = QtWidgets.QLabel(self.proxy_box)
        self.label_14.setText("@")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.proxy_server = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_server.setText("")
        self.proxy_server.setPlaceholderText("server")
        self.proxy_server.setObjectName("proxy_server")
        self.horizontalLayout_2.addWidget(self.proxy_server)
        self.label_15 = QtWidgets.QLabel(self.proxy_box)
        self.label_15.setText(":")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.proxy_port = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_port.setPlaceholderText("port")
        self.proxy_port.setObjectName("proxy_port")
        self.horizontalLayout_2.addWidget(self.proxy_port)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.proxy_box)
        self.scrollArea.setWidget(self.a2scroll_area_background)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.portable_label.setText(QtWidgets.QApplication.translate("Form", "a2 runs in portable mode! The data path is in the main directory and cannot be changed!", None, -1))

from a2widget.a2slider import A2Slider
from a2widget.a2path_field import A2PathField
