# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file:
#   'c:\Users\eric\io\code\a2\ui\a2widget\a2settings_view.ui'
# licensing of that file applies.
#
# Created: Wed Jul 15 13:59:33 2020
#      by: pyside2-uic  running on PySide2 5.15.0
#
# pylint: disable=W0201,C0103,C0111
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_a2settings:
    def setupUi(self, a2settings):
        a2settings.setObjectName("a2settings")
        a2settings.resize(794, 380)
        self.a2settings_view_layout = QtWidgets.QVBoxLayout(a2settings)
        self.a2settings_view_layout.setContentsMargins(0, 0, 0, 0)
        self.a2settings_view_layout.setObjectName("a2settings_view_layout")
        self.a2settings_tab = QtWidgets.QTabWidget(a2settings)
        self.a2settings_tab.setObjectName("a2settings_tab")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.main_tab)
        self.label_3.setText("Open a2 Dialog")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.a2hotkey = A2Hotkey(self.main_tab)
        self.a2hotkey.setEnabled(True)
        self.a2hotkey.setText("Win+Shift+A")
        self.a2hotkey.setObjectName("a2hotkey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.a2hotkey)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_on_win_start = QtWidgets.QCheckBox(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_on_win_start.sizePolicy().hasHeightForWidth())
        self.load_on_win_start.setSizePolicy(sizePolicy)
        self.load_on_win_start.setText("Load a2 on Windows Start")
        self.load_on_win_start.setObjectName("load_on_win_start")
        self.horizontalLayout_3.addWidget(self.load_on_win_start)
        self.load_on_win_start_alert = QtWidgets.QLabel(self.main_tab)
        self.load_on_win_start_alert.setMinimumSize(QtCore.QSize(16, 16))
        self.load_on_win_start_alert.setText("")
        self.load_on_win_start_alert.setObjectName("load_on_win_start_alert")
        self.horizontalLayout_3.addWidget(self.load_on_win_start_alert)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_desktop_shortcut = QtWidgets.QCheckBox(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_desktop_shortcut.sizePolicy().hasHeightForWidth())
        self.add_desktop_shortcut.setSizePolicy(sizePolicy)
        self.add_desktop_shortcut.setText("Add Shortcut to Desktop")
        self.add_desktop_shortcut.setObjectName("add_desktop_shortcut")
        self.horizontalLayout_5.addWidget(self.add_desktop_shortcut)
        self.add_desktop_shortcut_alert = QtWidgets.QLabel(self.main_tab)
        self.add_desktop_shortcut_alert.setMinimumSize(QtCore.QSize(16, 16))
        self.add_desktop_shortcut_alert.setText("")
        self.add_desktop_shortcut_alert.setObjectName("add_desktop_shortcut_alert")
        self.horizontalLayout_5.addWidget(self.add_desktop_shortcut_alert)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.remember_selection = QtWidgets.QCheckBox(self.main_tab)
        self.remember_selection.setText("Remember last selected Module")
        self.remember_selection.setObjectName("remember_selection")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.remember_selection)
        self.module_source_box = QtWidgets.QGroupBox(self.main_tab)
        self.module_source_box.setTitle("Module Sources")
        self.module_source_box.setObjectName("module_source_box")
        self.mod_source_box_layout = QtWidgets.QVBoxLayout(self.module_source_box)
        self.mod_source_box_layout.setSpacing(10)
        self.mod_source_box_layout.setContentsMargins(-1, 25, -1, -1)
        self.mod_source_box_layout.setObjectName("mod_source_box_layout")
        self.mod_source_layout = QtWidgets.QVBoxLayout()
        self.mod_source_layout.setObjectName("mod_source_layout")
        self.mod_source_box_layout.addLayout(self.mod_source_layout)
        self.no_sources_msg = QtWidgets.QLabel(self.module_source_box)
        self.no_sources_msg.setText("Currently there are no modules sources listed.\n"
"Go ahead and add or create one:")
        self.no_sources_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.no_sources_msg.setWordWrap(True)
        self.no_sources_msg.setObjectName("no_sources_msg")
        self.mod_source_box_layout.addWidget(self.no_sources_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a2add_button = QtWidgets.QPushButton(self.module_source_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a2add_button.sizePolicy().hasHeightForWidth())
        self.a2add_button.setSizePolicy(sizePolicy)
        self.a2add_button.setText("Add Source")
        self.a2add_button.setObjectName("a2add_button")
        self.horizontalLayout.addWidget(self.a2add_button)
        self.mod_source_box_layout.addLayout(self.horizontalLayout)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.module_source_box)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_startmenu_shortcuts = QtWidgets.QCheckBox(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_startmenu_shortcuts.sizePolicy().hasHeightForWidth())
        self.add_startmenu_shortcuts.setSizePolicy(sizePolicy)
        self.add_startmenu_shortcuts.setText("Add to Start Menu")
        self.add_startmenu_shortcuts.setObjectName("add_startmenu_shortcuts")
        self.horizontalLayout_6.addWidget(self.add_startmenu_shortcuts)
        self.add_startmenu_shortcuts_alert = QtWidgets.QLabel(self.main_tab)
        self.add_startmenu_shortcuts_alert.setMinimumSize(QtCore.QSize(16, 16))
        self.add_startmenu_shortcuts_alert.setText("")
        self.add_startmenu_shortcuts_alert.setObjectName("add_startmenu_shortcuts_alert")
        self.horizontalLayout_6.addWidget(self.add_startmenu_shortcuts_alert)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.a2settings_tab.addTab(self.main_tab, "a2 Settings")
        self.advanced_tab = QtWidgets.QWidget()
        self.advanced_tab.setObjectName("advanced_tab")
        self.a2settings_tab.addTab(self.advanced_tab, "")
        self.database_tab = QtWidgets.QWidget()
        self.database_tab.setObjectName("database_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.database_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.db_print_all_button = QtWidgets.QPushButton(self.database_tab)
        self.db_print_all_button.setText("get db digest")
        self.db_print_all_button.setObjectName("db_print_all_button")
        self.verticalLayout_5.addWidget(self.db_print_all_button)
        self.db_printout = QtWidgets.QTextEdit(self.database_tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.db_printout.setFont(font)
        self.db_printout.setReadOnly(True)
        self.db_printout.setObjectName("db_printout")
        self.verticalLayout_5.addWidget(self.db_printout)
        self.a2settings_tab.addTab(self.database_tab, "Database View")
        self.licenses_tab = QtWidgets.QWidget()
        self.licenses_tab.setObjectName("licenses_tab")
        self.a2settings_tab.addTab(self.licenses_tab, "Licenses")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.a2settings_tab.addTab(self.console_tab, "")
        self.a2settings_view_layout.addWidget(self.a2settings_tab)

        self.retranslateUi(a2settings)
        self.a2settings_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(a2settings)

    def retranslateUi(self, a2settings):
        self.a2settings_tab.setTabText(self.a2settings_tab.indexOf(self.advanced_tab), QtWidgets.QApplication.translate("a2settings", "Advanced", None, -1))
        self.a2settings_tab.setTabText(self.a2settings_tab.indexOf(self.console_tab), QtWidgets.QApplication.translate("a2settings", "Console", None, -1))

from a2widget.a2hotkey import A2Hotkey
