# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\eric\io\code\a2\ui\a2widget\a2settings_view.ui',
# licensing of 'c:\Users\eric\io\code\a2\ui\a2widget\a2settings_view.ui' applies.
#
# Created: Tue Jun 23 16:39:15 2020
#      by: pyside2-uic  running on PySide2 5.15.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_a2settings(object):
    def setupUi(self, a2settings):
        a2settings.setObjectName("a2settings")
        a2settings.resize(803, 674)
        a2settings.setWindowTitle("a2settings")
        a2settings.setStyleSheet("b")
        self.a2settings_view_layout = QtWidgets.QVBoxLayout(a2settings)
        self.a2settings_view_layout.setContentsMargins(0, 0, 0, 0)
        self.a2settings_view_layout.setObjectName("a2settings_view_layout")
        self.a2settings_tab = QtWidgets.QTabWidget(a2settings)
        self.a2settings_tab.setObjectName("a2settings_tab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("Q")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setText("Open a2 Dialog")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.a2hotkey = A2Hotkey(self.tab_2)
        self.a2hotkey.setEnabled(True)
        self.a2hotkey.setText("Win+Shift+A")
        self.a2hotkey.setObjectName("a2hotkey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.a2hotkey)
        self.load_on_win_start = QtWidgets.QCheckBox(self.tab_2)
        self.load_on_win_start.setText("Load a2 on Windows Start")
        self.load_on_win_start.setObjectName("load_on_win_start")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.load_on_win_start)
        self.remember_selection = QtWidgets.QCheckBox(self.tab_2)
        self.remember_selection.setText("Remember last selected Module")
        self.remember_selection.setObjectName("remember_selection")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.remember_selection)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(100, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.add_desktop_shortcut = QtWidgets.QCheckBox(self.tab_2)
        self.add_desktop_shortcut.setText("Add Shortcut to Desktop")
        self.add_desktop_shortcut.setObjectName("add_desktop_shortcut")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.add_desktop_shortcut)
        self.verticalLayout.addLayout(self.formLayout)
        self.module_source_box = QtWidgets.QGroupBox(self.tab_2)
        self.module_source_box.setTitle("Module Sources")
        self.module_source_box.setObjectName("module_source_box")
        self.mod_source_box_layout = QtWidgets.QVBoxLayout(self.module_source_box)
        self.mod_source_box_layout.setSpacing(10)
        self.mod_source_box_layout.setContentsMargins(-1, 25, -1, -1)
        self.mod_source_box_layout.setObjectName("mod_source_box_layout")
        self.mod_source_layout = QtWidgets.QVBoxLayout()
        self.mod_source_layout.setObjectName("mod_source_layout")
        self.mod_source_box_layout.addLayout(self.mod_source_layout)
        self.no_sources_msg = QtWidgets.QLabel(self.module_source_box)
        self.no_sources_msg.setText("Currently there are no modules sources listed.\n"
"Go ahead and add or create one:")
        self.no_sources_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.no_sources_msg.setWordWrap(True)
        self.no_sources_msg.setObjectName("no_sources_msg")
        self.mod_source_box_layout.addWidget(self.no_sources_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.a2add_button = QtWidgets.QPushButton(self.module_source_box)
        self.a2add_button.setText("Add Source")
        self.a2add_button.setObjectName("a2add_button")
        self.horizontalLayout.addWidget(self.a2add_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mod_source_box_layout.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.module_source_box)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.a2settings_tab.addTab(self.tab_2, "a2 Settings")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ui_scale_label = QtWidgets.QLabel(self.tab)
        self.ui_scale_label.setText("UI Scale:")
        self.ui_scale_label.setObjectName("ui_scale_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ui_scale_label)
        self.ui_scale_slider = A2Slider(self.tab)
        self.ui_scale_slider.setDecimals(2)
        self.ui_scale_slider.setMinimum(0.5)
        self.ui_scale_slider.setMaximum(2.0)
        self.ui_scale_slider.setSingleStep(0.05)
        self.ui_scale_slider.setProperty("value", 1.0)
        self.ui_scale_slider.setObjectName("ui_scale_slider")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ui_scale_slider)
        self.hotkey_box = QtWidgets.QGroupBox(self.tab)
        self.hotkey_box.setObjectName("hotkey_box")
        self.formLayout_4 = QtWidgets.QFormLayout(self.hotkey_box)
        self.formLayout_4.setContentsMargins(-1, 25, -1, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.hotkey_box)
        self.label_7.setText("Style:")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.hk_dialog_style = QtWidgets.QComboBox(self.hotkey_box)
        self.hk_dialog_style.setObjectName("hk_dialog_style")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hk_dialog_style)
        self.label_13 = QtWidgets.QLabel(self.hotkey_box)
        self.label_13.setText("Keyboard Layout:")
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.hk_dialog_layout = QtWidgets.QComboBox(self.hotkey_box)
        self.hk_dialog_layout.setObjectName("hk_dialog_layout")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hk_dialog_layout)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.hotkey_box)
        self.dev_box = QtWidgets.QGroupBox(self.tab)
        self.dev_box.setTitle("a2 dev mode")
        self.dev_box.setCheckable(True)
        self.dev_box.setObjectName("dev_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dev_box)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dev_widget = QtWidgets.QWidget(self.dev_box)
        self.dev_widget.setAccessibleDescription("")
        self.dev_widget.setObjectName("dev_widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dev_widget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dev_widget)
        self.label_4.setText("Author Name:")
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.author_name = QtWidgets.QLineEdit(self.dev_widget)
        self.author_name.setText("")
        self.author_name.setObjectName("author_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.author_name)
        self.label_6 = QtWidgets.QLabel(self.dev_widget)
        self.label_6.setText("Author Homepage:")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.author_url = QtWidgets.QLineEdit(self.dev_widget)
        self.author_url.setText("")
        self.author_url.setObjectName("author_url")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.author_url)
        self.label_5 = QtWidgets.QLabel(self.dev_widget)
        self.label_5.setText("Default Code Editor:")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.code_editor = A2PathField(self.dev_widget)
        self.code_editor.setText("")
        self.code_editor.setObjectName("code_editor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.code_editor)
        self.label_8 = QtWidgets.QLabel(self.dev_widget)
        self.label_8.setText("Autohotkey Executable:")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.autohotkey = A2PathField(self.dev_widget)
        self.autohotkey.setEnabled(False)
        self.autohotkey.setText("")
        self.autohotkey.setObjectName("autohotkey")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.autohotkey)
        self.label_12 = QtWidgets.QLabel(self.dev_widget)
        self.label_12.setEnabled(False)
        self.label_12.setText("a2 runtime:")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.startup_tooltips = QtWidgets.QCheckBox(self.dev_widget)
        self.startup_tooltips.setEnabled(False)
        self.startup_tooltips.setText("Enable Startup Tooltips")
        self.startup_tooltips.setObjectName("startup_tooltips")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.startup_tooltips)
        self.label_9 = QtWidgets.QLabel(self.dev_widget)
        self.label_9.setText("JSON Indent:")
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.json_indent = QtWidgets.QSpinBox(self.dev_widget)
        self.json_indent.setMaximumSize(QtCore.QSize(70, 16777215))
        self.json_indent.setObjectName("json_indent")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.json_indent)
        self.line = QtWidgets.QFrame(self.dev_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(100, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_2 = QtWidgets.QLabel(self.dev_widget)
        self.label_2.setText("User Data:")
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.data_folder = A2PathField(self.dev_widget)
        self.data_folder.setEnabled(False)
        self.data_folder.setText("")
        self.data_folder.setObjectName("data_folder")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.data_folder)
        self.label_10 = QtWidgets.QLabel(self.dev_widget)
        self.label_10.setText("Python Executable:")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.python_executable = A2PathField(self.dev_widget)
        self.python_executable.setEnabled(False)
        self.python_executable.setText("")
        self.python_executable.setObjectName("python_executable")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.python_executable)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_set_user_dir_standard = QtWidgets.QPushButton(self.dev_widget)
        self.button_set_user_dir_standard.setObjectName("button_set_user_dir_standard")
        self.horizontalLayout_4.addWidget(self.button_set_user_dir_standard)
        self.button_set_user_dir_custom = QtWidgets.QPushButton(self.dev_widget)
        self.button_set_user_dir_custom.setObjectName("button_set_user_dir_custom")
        self.horizontalLayout_4.addWidget(self.button_set_user_dir_custom)
        self.formLayout_2.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.dev_widget)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.dev_box)
        self.proxy_box = QtWidgets.QGroupBox(self.tab)
        self.proxy_box.setTitle("Use a Proxy")
        self.proxy_box.setCheckable(True)
        self.proxy_box.setChecked(False)
        self.proxy_box.setObjectName("proxy_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.proxy_box)
        self.verticalLayout_4.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.proxy_http = QtWidgets.QComboBox(self.proxy_box)
        self.proxy_http.setObjectName("proxy_http")
        self.proxy_http.addItem("")
        self.proxy_http.addItem("")
        self.horizontalLayout_2.addWidget(self.proxy_http)
        self.proxy_user = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_user.setPlaceholderText("user name")
        self.proxy_user.setObjectName("proxy_user")
        self.horizontalLayout_2.addWidget(self.proxy_user)
        self.label = QtWidgets.QLabel(self.proxy_box)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.proxy_pass = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.proxy_pass.setPlaceholderText("password")
        self.proxy_pass.setObjectName("proxy_pass")
        self.horizontalLayout_2.addWidget(self.proxy_pass)
        self.label_14 = QtWidgets.QLabel(self.proxy_box)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.proxy_server = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_server.setText("")
        self.proxy_server.setPlaceholderText("server")
        self.proxy_server.setObjectName("proxy_server")
        self.horizontalLayout_2.addWidget(self.proxy_server)
        self.label_15 = QtWidgets.QLabel(self.proxy_box)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.proxy_port = QtWidgets.QLineEdit(self.proxy_box)
        self.proxy_port.setPlaceholderText("port")
        self.proxy_port.setObjectName("proxy_port")
        self.horizontalLayout_2.addWidget(self.proxy_port)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.proxy_box)
        self.a2settings_tab.addTab(self.tab, "Advanced")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.db_print_all_button = QtWidgets.QPushButton(self.tab_4)
        self.db_print_all_button.setText("get db digest")
        self.db_print_all_button.setObjectName("db_print_all_button")
        self.verticalLayout_5.addWidget(self.db_print_all_button)
        self.db_printout = QtWidgets.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.db_printout.setFont(font)
        self.db_printout.setReadOnly(True)
        self.db_printout.setObjectName("db_printout")
        self.verticalLayout_5.addWidget(self.db_printout)
        self.a2settings_tab.addTab(self.tab_4, "Database View")
        self.licenses = QtWidgets.QWidget()
        self.licenses.setObjectName("licenses")
        self.a2settings_tab.addTab(self.licenses, "Licenses")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setObjectName("console_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.console_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.console = QtWidgets.QPlainTextEdit(self.console_tab)
        self.console.setObjectName("console")
        self.verticalLayout_2.addWidget(self.console)
        self.a2settings_tab.addTab(self.console_tab, "")
        self.a2settings_view_layout.addWidget(self.a2settings_tab)

        self.retranslateUi(a2settings)
        self.a2settings_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(a2settings)

    def retranslateUi(self, a2settings):
        self.hotkey_box.setTitle(QtWidgets.QApplication.translate("a2settings", "Hotkey Dialog", None, -1))
        self.button_set_user_dir_standard.setText(QtWidgets.QApplication.translate("a2settings", "Set User Dir Standard ", None, -1))
        self.button_set_user_dir_custom.setText(QtWidgets.QApplication.translate("a2settings", "Set Override Path", None, -1))
        self.proxy_http.setItemText(0, QtWidgets.QApplication.translate("a2settings", "http://", None, -1))
        self.proxy_http.setItemText(1, QtWidgets.QApplication.translate("a2settings", "https://", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("a2settings", ":", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("a2settings", "@", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("a2settings", ":", None, -1))
        self.a2settings_tab.setTabText(self.a2settings_tab.indexOf(self.console_tab), QtWidgets.QApplication.translate("a2settings", "Console", None, -1))

from a2widget.a2path_field import A2PathField
from a2widget.a2slider import A2Slider
from a2widget.a2hotkey import A2Hotkey
