# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\a2hotkey\hotkey_edit.ui'
#
# Created: Wed May  2 22:34:28 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_edit(object):
    def setupUi(self, edit):
        edit.setObjectName("edit")
        edit.resize(594, 204)
        self.edit_layout = QtGui.QFormLayout(edit)
        self.edit_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.edit_layout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.edit_layout.setObjectName("edit_layout")
        self.cfg_name = QtGui.QLineEdit(edit)
        self.cfg_name.setObjectName("cfg_name")
        self.edit_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfg_name)
        self.cfg_label = QtGui.QLineEdit(edit)
        self.cfg_label.setObjectName("cfg_label")
        self.edit_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cfg_label)
        self.hotkey_layout = QtGui.QVBoxLayout()
        self.hotkey_layout.setObjectName("hotkey_layout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hotkey_button = A2Hotkey(edit)
        self.hotkey_button.setEnabled(True)
        self.hotkey_button.setObjectName("hotkey_button")
        self.horizontalLayout_2.addWidget(self.hotkey_button)
        self.tool_button = QtGui.QToolButton(edit)
        self.tool_button.setText("...")
        self.tool_button.setAutoRaise(True)
        self.tool_button.setArrowType(QtCore.Qt.DownArrow)
        self.tool_button.setObjectName("tool_button")
        self.horizontalLayout_2.addWidget(self.tool_button)
        self.hotkey_layout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.cfg_enabled = QtGui.QCheckBox(edit)
        self.cfg_enabled.setChecked(True)
        self.cfg_enabled.setObjectName("cfg_enabled")
        self.gridLayout.addWidget(self.cfg_enabled, 0, 0, 1, 1)
        self.cfg_disablable = QtGui.QCheckBox(edit)
        self.cfg_disablable.setChecked(True)
        self.cfg_disablable.setObjectName("cfg_disablable")
        self.gridLayout.addWidget(self.cfg_disablable, 3, 0, 1, 1)
        self.cfg_keyChange = QtGui.QCheckBox(edit)
        self.cfg_keyChange.setChecked(True)
        self.cfg_keyChange.setObjectName("cfg_keyChange")
        self.gridLayout.addWidget(self.cfg_keyChange, 0, 1, 1, 1)
        self.cfg_multiple = QtGui.QCheckBox(edit)
        self.cfg_multiple.setChecked(True)
        self.cfg_multiple.setObjectName("cfg_multiple")
        self.gridLayout.addWidget(self.cfg_multiple, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.hotkey_layout.addLayout(self.gridLayout)
        self.edit_layout.setLayout(2, QtGui.QFormLayout.FieldRole, self.hotkey_layout)
        self.functionLabel = QtGui.QLabel(edit)
        self.functionLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.functionLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.functionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.functionLabel.setObjectName("functionLabel")
        self.edit_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.functionLabel)
        self.internalNameLabel = QtGui.QLabel(edit)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.internalNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.edit_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.internalNameLabel)
        self.displayLabelLabel = QtGui.QLabel(edit)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.displayLabelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.edit_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.displayLabelLabel)
        self.hotkeyLabel = QtGui.QLabel(edit)
        self.hotkeyLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.hotkeyLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hotkeyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hotkeyLabel.setObjectName("hotkeyLabel")
        self.edit_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.hotkeyLabel)
        self.func_widget = FuncWidget(edit)
        self.func_widget.setObjectName("func_widget")
        self.edit_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.func_widget)
        self.scopeLabel = QtGui.QLabel(edit)
        self.scopeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.scopeLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scopeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scopeLabel.setObjectName("scopeLabel")
        self.edit_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.scopeLabel)
        self.scope_widget = ScopeWidget(edit)
        self.scope_widget.setObjectName("scope_widget")
        self.edit_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.scope_widget)

        self.retranslateUi(edit)
        QtCore.QMetaObject.connectSlotsByName(edit)

    def retranslateUi(self, edit):
        edit.setWindowTitle(QtGui.QApplication.translate("edit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_name.setText(QtGui.QApplication.translate("edit", "extensionX_hotkey1", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_label.setText(QtGui.QApplication.translate("edit", "make some awesome stuff", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkey_button.setText(QtGui.QApplication.translate("edit", "Win+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_enabled.setText(QtGui.QApplication.translate("edit", "enabled by default", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_disablable.setText(QtGui.QApplication.translate("edit", "can be disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_keyChange.setText(QtGui.QApplication.translate("edit", "can be changed", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_multiple.setText(QtGui.QApplication.translate("edit", "allow multiple hotkeys", None, QtGui.QApplication.UnicodeUTF8))
        self.functionLabel.setText(QtGui.QApplication.translate("edit", "function:", None, QtGui.QApplication.UnicodeUTF8))
        self.internalNameLabel.setText(QtGui.QApplication.translate("edit", "internal name:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabelLabel.setText(QtGui.QApplication.translate("edit", "display label:", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyLabel.setText(QtGui.QApplication.translate("edit", "hotkey:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeLabel.setText(QtGui.QApplication.translate("edit", "scope:", None, QtGui.QApplication.UnicodeUTF8))

from a2widget.a2hotkey import A2Hotkey
from a2widget.a2hotkey.edit_scope_widget import ScopeWidget
from a2widget.a2hotkey.edit_func_widget import FuncWidget
