# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eric\io\code\a2\ui\a2widget\a2hotkey\scope_widget.ui',
# licensing of 'C:\Users\eric\io\code\a2\ui\a2widget\a2hotkey\scope_widget.ui' applies.
#
# Created: Sun Jun 17 23:09:57 2018
#      by: pyside2-uic  running on PySide2 5.11.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ScopeWidget(object):
    def setupUi(self, ScopeWidget):
        ScopeWidget.setObjectName("ScopeWidget")
        ScopeWidget.resize(500, 146)
        ScopeWidget.setWindowTitle("Form")
        ScopeWidget.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ScopeWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.type_radio_widget = QtWidgets.QWidget(ScopeWidget)
        self.type_radio_widget.setObjectName("type_radio_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.type_radio_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scopeMode_0 = QtWidgets.QRadioButton(self.type_radio_widget)
        self.scopeMode_0.setChecked(True)
        self.scopeMode_0.setObjectName("scopeMode_0")
        self.horizontalLayout.addWidget(self.scopeMode_0)
        self.scopeMode_1 = QtWidgets.QRadioButton(self.type_radio_widget)
        self.scopeMode_1.setChecked(False)
        self.scopeMode_1.setObjectName("scopeMode_1")
        self.horizontalLayout.addWidget(self.scopeMode_1)
        self.scopeMode_2 = QtWidgets.QRadioButton(self.type_radio_widget)
        self.scopeMode_2.setChecked(False)
        self.scopeMode_2.setObjectName("scopeMode_2")
        self.horizontalLayout.addWidget(self.scopeMode_2)
        self.horizontalLayout_2.addWidget(self.type_radio_widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.scope_help = QtWidgets.QToolButton(ScopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_help.sizePolicy().hasHeightForWidth())
        self.scope_help.setSizePolicy(sizePolicy)
        self.scope_help.setMaximumSize(QtCore.QSize(50, 35))
        self.scope_help.setToolTip("Help on Scopes")
        self.scope_help.setText("h")
        self.scope_help.setAutoRaise(True)
        self.scope_help.setObjectName("scope_help")
        self.horizontalLayout_2.addWidget(self.scope_help)
        self.tool_buttons_widget = QtWidgets.QWidget(ScopeWidget)
        self.tool_buttons_widget.setObjectName("tool_buttons_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tool_buttons_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scope_pick = QtWidgets.QToolButton(self.tool_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_pick.sizePolicy().hasHeightForWidth())
        self.scope_pick.setSizePolicy(sizePolicy)
        self.scope_pick.setMaximumSize(QtCore.QSize(50, 35))
        self.scope_pick.setToolTip("Pick from a Window")
        self.scope_pick.setText("p")
        self.scope_pick.setAutoRaise(True)
        self.scope_pick.setObjectName("scope_pick")
        self.horizontalLayout_3.addWidget(self.scope_pick)
        self.scope_delete = QtWidgets.QToolButton(self.tool_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_delete.sizePolicy().hasHeightForWidth())
        self.scope_delete.setSizePolicy(sizePolicy)
        self.scope_delete.setMaximumSize(QtCore.QSize(50, 35))
        self.scope_delete.setToolTip("Delete Selected Scope")
        self.scope_delete.setText("-")
        self.scope_delete.setAutoRaise(True)
        self.scope_delete.setObjectName("scope_delete")
        self.horizontalLayout_3.addWidget(self.scope_delete)
        self.scope_add = QtWidgets.QToolButton(self.tool_buttons_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_add.sizePolicy().hasHeightForWidth())
        self.scope_add.setSizePolicy(sizePolicy)
        self.scope_add.setMaximumSize(QtCore.QSize(50, 35))
        self.scope_add.setToolTip("Add a Scope")
        self.scope_add.setText("+")
        self.scope_add.setAutoRaise(True)
        self.scope_add.setObjectName("scope_add")
        self.horizontalLayout_3.addWidget(self.scope_add)
        self.horizontalLayout_2.addWidget(self.tool_buttons_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cfg_scope = A2ListCompact(ScopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfg_scope.sizePolicy().hasHeightForWidth())
        self.cfg_scope.setSizePolicy(sizePolicy)
        self.cfg_scope.setMinimumSize(QtCore.QSize(500, 40))
        self.cfg_scope.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cfg_scope.setToolTip("")
        self.cfg_scope.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cfg_scope.setObjectName("cfg_scope")
        self.verticalLayout.addWidget(self.cfg_scope)
        self.fields_widget = QtWidgets.QWidget(ScopeWidget)
        self.fields_widget.setObjectName("fields_widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.fields_widget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.fields_widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.scope_title = A2ButtonField(self.fields_widget)
        self.scope_title.setObjectName("scope_title")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scope_title)
        self.label_3 = QtWidgets.QLabel(self.fields_widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.scope_class = A2ButtonField(self.fields_widget)
        self.scope_class.setObjectName("scope_class")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scope_class)
        self.label_4 = QtWidgets.QLabel(self.fields_widget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.scope_exe = A2ButtonField(self.fields_widget)
        self.scope_exe.setObjectName("scope_exe")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scope_exe)
        self.verticalLayout.addWidget(self.fields_widget)

        self.retranslateUi(ScopeWidget)
        QtCore.QMetaObject.connectSlotsByName(ScopeWidget)

    def retranslateUi(self, ScopeWidget):
        self.scopeMode_0.setToolTip(QtWidgets.QApplication.translate("ScopeWidget", "global - Makes it work anywhere in the system.", None, -1))
        self.scopeMode_0.setText(QtWidgets.QApplication.translate("ScopeWidget", "golbal", None, -1))
        self.scopeMode_1.setToolTip(QtWidgets.QApplication.translate("ScopeWidget", "include - To make it work ONLY in certain windows.", None, -1))
        self.scopeMode_1.setText(QtWidgets.QApplication.translate("ScopeWidget", "include:", None, -1))
        self.scopeMode_2.setToolTip(QtWidgets.QApplication.translate("ScopeWidget", "exclude - To make it work anywhere BUT not in given windows.", None, -1))
        self.scopeMode_2.setText(QtWidgets.QApplication.translate("ScopeWidget", "exclude:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ScopeWidget", "title", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ScopeWidget", "window class", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ScopeWidget", "executable", None, -1))

from a2widget import A2ListCompact, A2ButtonField
