# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\a2design.ui'
#
# Created: Tue Apr 28 00:46:40 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_a2MainWindow(object):
    def setupUi(self, a2MainWindow):
        a2MainWindow.setObjectName("a2MainWindow")
        a2MainWindow.resize(1230, 713)
        self.centralwidget = QtGui.QWidget(a2MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.moduleBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleBox.sizePolicy().hasHeightForWidth())
        self.moduleBox.setSizePolicy(sizePolicy)
        self.moduleBox.setMinimumSize(QtCore.QSize(100, 0))
        self.moduleBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.moduleBox.setBaseSize(QtCore.QSize(26, 0))
        self.moduleBox.setObjectName("moduleBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.moduleBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modList = QtGui.QListWidget(self.moduleBox)
        self.modList.setObjectName("modList")
        self.verticalLayout_2.addWidget(self.modList)
        self.settingsBox = QtGui.QGroupBox(self.splitter)
        self.settingsBox.setTitle("")
        self.settingsBox.setObjectName("settingsBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.settingsBox)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modCheck = QtGui.QCheckBox(self.settingsBox)
        self.modCheck.setText("")
        self.modCheck.setObjectName("modCheck")
        self.horizontalLayout.addWidget(self.modCheck)
        self.modName = QtGui.QLabel(self.settingsBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.modName.setFont(font)
        self.modName.setToolTip("")
        self.modName.setStatusTip("")
        self.modName.setWhatsThis("")
        self.modName.setAccessibleName("")
        self.modName.setAccessibleDescription("")
        self.modName.setText("ModName")
        self.modName.setTextFormat(QtCore.Qt.PlainText)
        self.modName.setObjectName("modName")
        self.horizontalLayout.addWidget(self.modName)
        self.modVersion = QtGui.QLabel(self.settingsBox)
        self.modVersion.setObjectName("modVersion")
        self.horizontalLayout.addWidget(self.modVersion)
        self.modAuthor = QtGui.QLabel(self.settingsBox)
        self.modAuthor.setObjectName("modAuthor")
        self.horizontalLayout.addWidget(self.modAuthor)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.modInfoButton = QtGui.QPushButton(self.settingsBox)
        self.modInfoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.modInfoButton.setObjectName("modInfoButton")
        self.horizontalLayout.addWidget(self.modInfoButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtGui.QScrollArea(self.settingsBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContents = QtGui.QWidget()
        self.scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 796, 565))
        self.scrollAreaContents.setObjectName("scrollAreaContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.welcomeText = QtGui.QLabel(self.scrollAreaContents)
        self.welcomeText.setAutoFillBackground(False)
        self.welcomeText.setWordWrap(True)
        self.welcomeText.setObjectName("welcomeText")
        self.verticalLayout_4.addWidget(self.welcomeText)
        self.scrollArea.setWidget(self.scrollAreaContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.splitter)
        a2MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(a2MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 38))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        a2MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(a2MainWindow)
        self.statusbar.setObjectName("statusbar")
        a2MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_a2 = QtGui.QAction(a2MainWindow)
        self.actionAbout_a2.setObjectName("actionAbout_a2")
        self.menuHelp.addAction(self.actionAbout_a2)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(a2MainWindow)
        QtCore.QMetaObject.connectSlotsByName(a2MainWindow)

    def retranslateUi(self, a2MainWindow):
        a2MainWindow.setWindowTitle(QtGui.QApplication.translate("a2MainWindow", "a2", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleBox.setTitle(QtGui.QApplication.translate("a2MainWindow", "modules", None, QtGui.QApplication.UnicodeUTF8))
        self.modVersion.setText(QtGui.QApplication.translate("a2MainWindow", "v0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.modAuthor.setText(QtGui.QApplication.translate("a2MainWindow", "- Author Name", None, QtGui.QApplication.UnicodeUTF8))
        self.modInfoButton.setText(QtGui.QApplication.translate("a2MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.welcomeText.setText(QtGui.QApplication.translate("a2MainWindow", "Hello user! Welcome to a2! This is a template introduction Text. So far there is not much to say. I just wanted this to fill up more than one line properly. Voila!", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("a2MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_a2.setText(QtGui.QApplication.translate("a2MainWindow", "about a2", None, QtGui.QApplication.UnicodeUTF8))

