# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\a2design.ui'
#
# Created: Fri May 22 19:19:55 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_a2MainWindow(object):
    def setupUi(self, a2MainWindow):
        a2MainWindow.setObjectName("a2MainWindow")
        a2MainWindow.resize(1196, 679)
        self.centralwidget = QtGui.QWidget(a2MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.moduleBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleBox.sizePolicy().hasHeightForWidth())
        self.moduleBox.setSizePolicy(sizePolicy)
        self.moduleBox.setMinimumSize(QtCore.QSize(100, 0))
        self.moduleBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.moduleBox.setBaseSize(QtCore.QSize(26, 0))
        self.moduleBox.setObjectName("moduleBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.moduleBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modList = QtGui.QListWidget(self.moduleBox)
        self.modList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.modList.setAlternatingRowColors(True)
        self.modList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.modList.setIconSize(QtCore.QSize(32, 32))
        self.modList.setSelectionRectVisible(False)
        self.modList.setObjectName("modList")
        self.verticalLayout_2.addWidget(self.modList)
        self.settingsBox = QtGui.QGroupBox(self.splitter)
        self.settingsBox.setTitle("")
        self.settingsBox.setObjectName("settingsBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.settingsBox)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsHeadLayout = QtGui.QHBoxLayout()
        self.settingsHeadLayout.setObjectName("settingsHeadLayout")
        self.modCheck = QtGui.QCheckBox(self.settingsBox)
        self.modCheck.setText("")
        self.modCheck.setObjectName("modCheck")
        self.settingsHeadLayout.addWidget(self.modCheck)
        self.modName = QtGui.QLabel(self.settingsBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.modName.setFont(font)
        self.modName.setToolTip("")
        self.modName.setStatusTip("")
        self.modName.setWhatsThis("")
        self.modName.setAccessibleName("")
        self.modName.setAccessibleDescription("")
        self.modName.setText("ModName")
        self.modName.setTextFormat(QtCore.Qt.PlainText)
        self.modName.setObjectName("modName")
        self.settingsHeadLayout.addWidget(self.modName)
        self.modVersion = QtGui.QLabel(self.settingsBox)
        self.modVersion.setObjectName("modVersion")
        self.settingsHeadLayout.addWidget(self.modVersion)
        self.modAuthor = QtGui.QLabel(self.settingsBox)
        self.modAuthor.setObjectName("modAuthor")
        self.settingsHeadLayout.addWidget(self.modAuthor)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.settingsHeadLayout.addItem(spacerItem)
        self.modInfoButton = QtGui.QPushButton(self.settingsBox)
        self.modInfoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.modInfoButton.setObjectName("modInfoButton")
        self.settingsHeadLayout.addWidget(self.modInfoButton)
        self.verticalLayout.addLayout(self.settingsHeadLayout)
        self.scrollArea = QtGui.QScrollArea(self.settingsBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContents = QtGui.QWidget()
        self.scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 762, 523))
        self.scrollAreaContents.setObjectName("scrollAreaContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.welcomeText = QtGui.QLabel(self.scrollAreaContents)
        self.welcomeText.setAutoFillBackground(False)
        self.welcomeText.setWordWrap(True)
        self.welcomeText.setObjectName("welcomeText")
        self.verticalLayout_4.addWidget(self.welcomeText)
        self.scrollArea.setWidget(self.scrollAreaContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.editOKCancelLayout = QtGui.QHBoxLayout()
        self.editOKCancelLayout.setContentsMargins(-1, -1, -1, 5)
        self.editOKCancelLayout.setObjectName("editOKCancelLayout")
        self.editOKButton = QtGui.QPushButton(self.settingsBox)
        self.editOKButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.editOKButton.setObjectName("editOKButton")
        self.editOKCancelLayout.addWidget(self.editOKButton)
        self.editCancelButton = QtGui.QPushButton(self.settingsBox)
        self.editCancelButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.editCancelButton.setObjectName("editCancelButton")
        self.editOKCancelLayout.addWidget(self.editCancelButton)
        self.verticalLayout.addLayout(self.editOKCancelLayout)
        self.verticalLayout_3.addWidget(self.splitter)
        a2MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(a2MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 38))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDev = QtGui.QMenu(self.menubar)
        self.menuDev.setObjectName("menuDev")
        a2MainWindow.setMenuBar(self.menubar)
        self.actionAbout_a2 = QtGui.QAction(a2MainWindow)
        self.actionAbout_a2.setObjectName("actionAbout_a2")
        self.actionEdit_module = QtGui.QAction(a2MainWindow)
        self.actionEdit_module.setObjectName("actionEdit_module")
        self.actionDisable_all_modules = QtGui.QAction(a2MainWindow)
        self.actionDisable_all_modules.setObjectName("actionDisable_all_modules")
        self.actionExplore_to = QtGui.QAction(a2MainWindow)
        self.actionExplore_to.setObjectName("actionExplore_to")
        self.menuHelp.addAction(self.actionAbout_a2)
        self.menuDev.addAction(self.actionEdit_module)
        self.menuDev.addAction(self.actionDisable_all_modules)
        self.menuDev.addAction(self.actionExplore_to)
        self.menubar.addAction(self.menuDev.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(a2MainWindow)
        self.modList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(a2MainWindow)

    def retranslateUi(self, a2MainWindow):
        a2MainWindow.setWindowTitle(QtGui.QApplication.translate("a2MainWindow", "a2", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleBox.setTitle(QtGui.QApplication.translate("a2MainWindow", "modules", None, QtGui.QApplication.UnicodeUTF8))
        self.modVersion.setText(QtGui.QApplication.translate("a2MainWindow", "v0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.modAuthor.setText(QtGui.QApplication.translate("a2MainWindow", "- Author Name", None, QtGui.QApplication.UnicodeUTF8))
        self.modInfoButton.setText(QtGui.QApplication.translate("a2MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.welcomeText.setText(QtGui.QApplication.translate("a2MainWindow", "Hello user! Welcome to a2! This is a template introduction Text. So far there is not much to say. I just wanted this to fill up more than one line properly. Voila!", None, QtGui.QApplication.UnicodeUTF8))
        self.editOKButton.setText(QtGui.QApplication.translate("a2MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.editCancelButton.setText(QtGui.QApplication.translate("a2MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("a2MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDev.setTitle(QtGui.QApplication.translate("a2MainWindow", "&Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_a2.setText(QtGui.QApplication.translate("a2MainWindow", "about a2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_module.setText(QtGui.QApplication.translate("a2MainWindow", "edit module", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisable_all_modules.setText(QtGui.QApplication.translate("a2MainWindow", "disable all modules", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplore_to.setText(QtGui.QApplication.translate("a2MainWindow", "explore to ...", None, QtGui.QApplication.UnicodeUTF8))

