# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\hotkey_edit.ui'
#
# Created: Fri Jun 19 20:17:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_hotkey_edit(object):
    def setupUi(self, hotkey_edit):
        hotkey_edit.setObjectName("hotkey_edit")
        hotkey_edit.resize(1084, 665)
        self.hotkeyCtrlLayout = QtGui.QVBoxLayout(hotkey_edit)
        self.hotkeyCtrlLayout.setSpacing(0)
        self.hotkeyCtrlLayout.setContentsMargins(0, 0, 0, 0)
        self.hotkeyCtrlLayout.setObjectName("hotkeyCtrlLayout")
        self.groupBox = QtGui.QGroupBox(hotkey_edit)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.internalNameLayout = QtGui.QHBoxLayout()
        self.internalNameLayout.setObjectName("internalNameLayout")
        self.internalNameLabel = QtGui.QLabel(self.groupBox)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.internalNameLayout.addWidget(self.internalNameLabel)
        self.cfg_name = QtGui.QLineEdit(self.groupBox)
        self.cfg_name.setObjectName("cfg_name")
        self.internalNameLayout.addWidget(self.cfg_name)
        self.verticalLayout_2.addLayout(self.internalNameLayout)
        self.displayLabelLayout = QtGui.QHBoxLayout()
        self.displayLabelLayout.setObjectName("displayLabelLayout")
        self.displayLabelLabel = QtGui.QLabel(self.groupBox)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.displayLabelLayout.addWidget(self.displayLabelLabel)
        self.cfg_label = QtGui.QLineEdit(self.groupBox)
        self.cfg_label.setObjectName("cfg_label")
        self.displayLabelLayout.addWidget(self.cfg_label)
        self.verticalLayout_2.addLayout(self.displayLabelLayout)
        self.hotkeyLayout = QtGui.QHBoxLayout()
        self.hotkeyLayout.setContentsMargins(-1, -1, -1, 10)
        self.hotkeyLayout.setObjectName("hotkeyLayout")
        self.hotkeyLabelLayout = QtGui.QVBoxLayout()
        self.hotkeyLabelLayout.setObjectName("hotkeyLabelLayout")
        self.hotkeyLabel = QtGui.QLabel(self.groupBox)
        self.hotkeyLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.hotkeyLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hotkeyLabel.setObjectName("hotkeyLabel")
        self.hotkeyLabelLayout.addWidget(self.hotkeyLabel)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hotkeyLabelLayout.addItem(spacerItem)
        self.hotkeyLayout.addLayout(self.hotkeyLabelLayout)
        self.hotkeyKeyLayout = QtGui.QVBoxLayout()
        self.hotkeyKeyLayout.setSpacing(5)
        self.hotkeyKeyLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.hotkeyKeyLayout.setObjectName("hotkeyKeyLayout")
        self.hotkeyButton = QtGui.QPushButton(self.groupBox)
        self.hotkeyButton.setObjectName("hotkeyButton")
        self.hotkeyKeyLayout.addWidget(self.hotkeyButton)
        self.cfg_enabled = QtGui.QCheckBox(self.groupBox)
        self.cfg_enabled.setChecked(True)
        self.cfg_enabled.setObjectName("cfg_enabled")
        self.hotkeyKeyLayout.addWidget(self.cfg_enabled)
        self.cfg_disablable = QtGui.QCheckBox(self.groupBox)
        self.cfg_disablable.setChecked(True)
        self.cfg_disablable.setObjectName("cfg_disablable")
        self.hotkeyKeyLayout.addWidget(self.cfg_disablable)
        self.cfg_keyChange = QtGui.QCheckBox(self.groupBox)
        self.cfg_keyChange.setChecked(True)
        self.cfg_keyChange.setObjectName("cfg_keyChange")
        self.hotkeyKeyLayout.addWidget(self.cfg_keyChange)
        self.cfg_multiple = QtGui.QCheckBox(self.groupBox)
        self.cfg_multiple.setChecked(True)
        self.cfg_multiple.setObjectName("cfg_multiple")
        self.hotkeyKeyLayout.addWidget(self.cfg_multiple)
        self.hotkeyLayout.addLayout(self.hotkeyKeyLayout)
        self.hotkeyLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.hotkeyLayout)
        self.scopeLayout = QtGui.QHBoxLayout()
        self.scopeLayout.setContentsMargins(-1, -1, -1, 10)
        self.scopeLayout.setObjectName("scopeLayout")
        self.scopeLabelLayout = QtGui.QVBoxLayout()
        self.scopeLabelLayout.setObjectName("scopeLabelLayout")
        self.scopeLabel = QtGui.QLabel(self.groupBox)
        self.scopeLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.scopeLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scopeLabel.setObjectName("scopeLabel")
        self.scopeLabelLayout.addWidget(self.scopeLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.scopeLabelLayout.addItem(spacerItem1)
        self.scopeLayout.addLayout(self.scopeLabelLayout)
        self.scopeCtrlLayout = QtGui.QVBoxLayout()
        self.scopeCtrlLayout.setSpacing(5)
        self.scopeCtrlLayout.setContentsMargins(-1, -1, -1, 0)
        self.scopeCtrlLayout.setObjectName("scopeCtrlLayout")
        self.scopeRowLayout = QtGui.QHBoxLayout()
        self.scopeRowLayout.setContentsMargins(-1, 0, -1, -1)
        self.scopeRowLayout.setObjectName("scopeRowLayout")
        self.scopeEverywhere = QtGui.QRadioButton(self.groupBox)
        self.scopeEverywhere.setChecked(True)
        self.scopeEverywhere.setObjectName("scopeEverywhere")
        self.scopeRowLayout.addWidget(self.scopeEverywhere)
        self.scopeEnableIn = QtGui.QRadioButton(self.groupBox)
        self.scopeEnableIn.setObjectName("scopeEnableIn")
        self.scopeRowLayout.addWidget(self.scopeEnableIn)
        self.scopeDisableIn = QtGui.QRadioButton(self.groupBox)
        self.scopeDisableIn.setObjectName("scopeDisableIn")
        self.scopeRowLayout.addWidget(self.scopeDisableIn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scopeRowLayout.addItem(spacerItem2)
        self.scopeCtrlLayout.addLayout(self.scopeRowLayout)
        self.cfg_scope = QtGui.QListView(self.groupBox)
        self.cfg_scope.setObjectName("cfg_scope")
        self.scopeCtrlLayout.addWidget(self.cfg_scope)
        self.cfg_scopeChange = QtGui.QCheckBox(self.groupBox)
        self.cfg_scopeChange.setChecked(True)
        self.cfg_scopeChange.setObjectName("cfg_scopeChange")
        self.scopeCtrlLayout.addWidget(self.cfg_scopeChange)
        self.scopeLayout.addLayout(self.scopeCtrlLayout)
        self.scopeLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.scopeLayout)
        self.scopeLayout_3 = QtGui.QHBoxLayout()
        self.scopeLayout_3.setObjectName("scopeLayout_3")
        self.scopeLabelLayout_3 = QtGui.QVBoxLayout()
        self.scopeLabelLayout_3.setObjectName("scopeLabelLayout_3")
        self.scopeLabel_3 = QtGui.QLabel(self.groupBox)
        self.scopeLabel_3.setMinimumSize(QtCore.QSize(200, 0))
        self.scopeLabel_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scopeLabel_3.setObjectName("scopeLabel_3")
        self.scopeLabelLayout_3.addWidget(self.scopeLabel_3)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.scopeLabelLayout_3.addItem(spacerItem3)
        self.scopeLayout_3.addLayout(self.scopeLabelLayout_3)
        self.scopeCtrlLayout_3 = QtGui.QVBoxLayout()
        self.scopeCtrlLayout_3.setSpacing(6)
        self.scopeCtrlLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.scopeCtrlLayout_3.setObjectName("scopeCtrlLayout_3")
        self.scopeRowLayout_3 = QtGui.QHBoxLayout()
        self.scopeRowLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.scopeRowLayout_3.setObjectName("scopeRowLayout_3")
        self.scopeEverywhere_3 = QtGui.QRadioButton(self.groupBox)
        self.scopeEverywhere_3.setChecked(True)
        self.scopeEverywhere_3.setObjectName("scopeEverywhere_3")
        self.scopeRowLayout_3.addWidget(self.scopeEverywhere_3)
        self.scopeEnableIn_3 = QtGui.QRadioButton(self.groupBox)
        self.scopeEnableIn_3.setObjectName("scopeEnableIn_3")
        self.scopeRowLayout_3.addWidget(self.scopeEnableIn_3)
        self.scopeDisableIn_3 = QtGui.QRadioButton(self.groupBox)
        self.scopeDisableIn_3.setObjectName("scopeDisableIn_3")
        self.scopeRowLayout_3.addWidget(self.scopeDisableIn_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scopeRowLayout_3.addItem(spacerItem4)
        self.scopeCtrlLayout_3.addLayout(self.scopeRowLayout_3)
        self.scopeLayout_3.addLayout(self.scopeCtrlLayout_3)
        self.scopeLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.scopeLayout_3)
        self.hotkeyCtrlLayout.addWidget(self.groupBox)

        self.retranslateUi(hotkey_edit)
        QtCore.QMetaObject.connectSlotsByName(hotkey_edit)

    def retranslateUi(self, hotkey_edit):
        hotkey_edit.setWindowTitle(QtGui.QApplication.translate("hotkey_edit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("hotkey_edit", "hotkey", None, QtGui.QApplication.UnicodeUTF8))
        self.internalNameLabel.setText(QtGui.QApplication.translate("hotkey_edit", "internal name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_name.setText(QtGui.QApplication.translate("hotkey_edit", "extensionXhotkey1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabelLabel.setText(QtGui.QApplication.translate("hotkey_edit", "display label:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_label.setText(QtGui.QApplication.translate("hotkey_edit", "make some awesome stuff", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyLabel.setText(QtGui.QApplication.translate("hotkey_edit", "standard hotkey:", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyButton.setText(QtGui.QApplication.translate("hotkey_edit", "Win+G", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_enabled.setText(QtGui.QApplication.translate("hotkey_edit", "enabled by default", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_disablable.setText(QtGui.QApplication.translate("hotkey_edit", "can be disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_keyChange.setText(QtGui.QApplication.translate("hotkey_edit", "can be changed", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_multiple.setText(QtGui.QApplication.translate("hotkey_edit", "allow multiple hotkeys", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeLabel.setText(QtGui.QApplication.translate("hotkey_edit", "scope", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEverywhere.setText(QtGui.QApplication.translate("hotkey_edit", "everywhere", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEnableIn.setText(QtGui.QApplication.translate("hotkey_edit", "only in:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeDisableIn.setText(QtGui.QApplication.translate("hotkey_edit", "everywhere but:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_scopeChange.setText(QtGui.QApplication.translate("hotkey_edit", "can be changed", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeLabel_3.setText(QtGui.QApplication.translate("hotkey_edit", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEverywhere_3.setText(QtGui.QApplication.translate("hotkey_edit", "run code:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEnableIn_3.setText(QtGui.QApplication.translate("hotkey_edit", "open file:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeDisableIn_3.setText(QtGui.QApplication.translate("hotkey_edit", "send keystrokes:", None, QtGui.QApplication.UnicodeUTF8))

