# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\hotkey_edit.ui'
#
# Created: Tue Jun 16 00:17:54 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_hotkey_edit(object):
    def setupUi(self, hotkey_edit):
        hotkey_edit.setObjectName("hotkey_edit")
        hotkey_edit.resize(1084, 636)
        self.verticalLayout = QtGui.QVBoxLayout(hotkey_edit)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(hotkey_edit)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.internalNameLayout = QtGui.QHBoxLayout()
        self.internalNameLayout.setObjectName("internalNameLayout")
        self.internalNameLabel = QtGui.QLabel(self.groupBox)
        self.internalNameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.internalNameLabel.setObjectName("internalNameLabel")
        self.internalNameLayout.addWidget(self.internalNameLabel)
        self.internalName = QtGui.QLineEdit(self.groupBox)
        self.internalName.setObjectName("internalName")
        self.internalNameLayout.addWidget(self.internalName)
        self.verticalLayout_2.addLayout(self.internalNameLayout)
        self.displayLabelLayout = QtGui.QHBoxLayout()
        self.displayLabelLayout.setObjectName("displayLabelLayout")
        self.displayLabelLabel = QtGui.QLabel(self.groupBox)
        self.displayLabelLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.displayLabelLabel.setObjectName("displayLabelLabel")
        self.displayLabelLayout.addWidget(self.displayLabelLabel)
        self.displayLabel = QtGui.QLineEdit(self.groupBox)
        self.displayLabel.setObjectName("displayLabel")
        self.displayLabelLayout.addWidget(self.displayLabel)
        self.verticalLayout_2.addLayout(self.displayLabelLayout)
        self.hotkeyLayout = QtGui.QHBoxLayout()
        self.hotkeyLayout.setObjectName("hotkeyLayout")
        self.hotkeyLabelLayout = QtGui.QVBoxLayout()
        self.hotkeyLabelLayout.setObjectName("hotkeyLabelLayout")
        self.hotkeyLabel = QtGui.QLabel(self.groupBox)
        self.hotkeyLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.hotkeyLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hotkeyLabel.setObjectName("hotkeyLabel")
        self.hotkeyLabelLayout.addWidget(self.hotkeyLabel)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hotkeyLabelLayout.addItem(spacerItem)
        self.hotkeyLayout.addLayout(self.hotkeyLabelLayout)
        self.hotkeyKeyLayout = QtGui.QVBoxLayout()
        self.hotkeyKeyLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.hotkeyKeyLayout.setObjectName("hotkeyKeyLayout")
        self.hotkeyButton = QtGui.QPushButton(self.groupBox)
        self.hotkeyButton.setObjectName("hotkeyButton")
        self.hotkeyKeyLayout.addWidget(self.hotkeyButton)
        self.hotkeyEnabled = QtGui.QCheckBox(self.groupBox)
        self.hotkeyEnabled.setChecked(True)
        self.hotkeyEnabled.setObjectName("hotkeyEnabled")
        self.hotkeyKeyLayout.addWidget(self.hotkeyEnabled)
        self.hotkeyDisablable = QtGui.QCheckBox(self.groupBox)
        self.hotkeyDisablable.setChecked(True)
        self.hotkeyDisablable.setObjectName("hotkeyDisablable")
        self.hotkeyKeyLayout.addWidget(self.hotkeyDisablable)
        self.hotkeyChangable = QtGui.QCheckBox(self.groupBox)
        self.hotkeyChangable.setChecked(True)
        self.hotkeyChangable.setObjectName("hotkeyChangable")
        self.hotkeyKeyLayout.addWidget(self.hotkeyChangable)
        self.hotkeyMultiple = QtGui.QCheckBox(self.groupBox)
        self.hotkeyMultiple.setChecked(True)
        self.hotkeyMultiple.setObjectName("hotkeyMultiple")
        self.hotkeyKeyLayout.addWidget(self.hotkeyMultiple)
        self.hotkeyLayout.addLayout(self.hotkeyKeyLayout)
        self.hotkeyLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.hotkeyLayout)
        self.scopeLayout = QtGui.QHBoxLayout()
        self.scopeLayout.setObjectName("scopeLayout")
        self.scopeLabelLayout = QtGui.QVBoxLayout()
        self.scopeLabelLayout.setObjectName("scopeLabelLayout")
        self.scopeLabel = QtGui.QLabel(self.groupBox)
        self.scopeLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.scopeLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scopeLabel.setObjectName("scopeLabel")
        self.scopeLabelLayout.addWidget(self.scopeLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.scopeLabelLayout.addItem(spacerItem1)
        self.scopeLayout.addLayout(self.scopeLabelLayout)
        self.scopeCtrlLayout = QtGui.QVBoxLayout()
        self.scopeCtrlLayout.setSpacing(6)
        self.scopeCtrlLayout.setContentsMargins(-1, -1, -1, 0)
        self.scopeCtrlLayout.setObjectName("scopeCtrlLayout")
        self.scopeRowLayout = QtGui.QHBoxLayout()
        self.scopeRowLayout.setContentsMargins(-1, 0, -1, -1)
        self.scopeRowLayout.setObjectName("scopeRowLayout")
        self.scopeEverywhere = QtGui.QRadioButton(self.groupBox)
        self.scopeEverywhere.setChecked(True)
        self.scopeEverywhere.setObjectName("scopeEverywhere")
        self.scopeRowLayout.addWidget(self.scopeEverywhere)
        self.scopeEnableIn = QtGui.QRadioButton(self.groupBox)
        self.scopeEnableIn.setObjectName("scopeEnableIn")
        self.scopeRowLayout.addWidget(self.scopeEnableIn)
        self.scopeDisableIn = QtGui.QRadioButton(self.groupBox)
        self.scopeDisableIn.setObjectName("scopeDisableIn")
        self.scopeRowLayout.addWidget(self.scopeDisableIn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scopeRowLayout.addItem(spacerItem2)
        self.scopeCtrlLayout.addLayout(self.scopeRowLayout)
        self.scopeList = QtGui.QListView(self.groupBox)
        self.scopeList.setObjectName("scopeList")
        self.scopeCtrlLayout.addWidget(self.scopeList)
        self.scopeChangable = QtGui.QCheckBox(self.groupBox)
        self.scopeChangable.setChecked(True)
        self.scopeChangable.setObjectName("scopeChangable")
        self.scopeCtrlLayout.addWidget(self.scopeChangable)
        self.scopeLayout.addLayout(self.scopeCtrlLayout)
        self.scopeLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.scopeLayout)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(hotkey_edit)
        QtCore.QMetaObject.connectSlotsByName(hotkey_edit)

    def retranslateUi(self, hotkey_edit):
        hotkey_edit.setWindowTitle(QtGui.QApplication.translate("hotkey_edit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("hotkey_edit", "hotkey", None, QtGui.QApplication.UnicodeUTF8))
        self.internalNameLabel.setText(QtGui.QApplication.translate("hotkey_edit", "internal name", None, QtGui.QApplication.UnicodeUTF8))
        self.internalName.setText(QtGui.QApplication.translate("hotkey_edit", "extensionXhotkey1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabelLabel.setText(QtGui.QApplication.translate("hotkey_edit", "display label", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabel.setText(QtGui.QApplication.translate("hotkey_edit", "make some awesome stuff", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyLabel.setText(QtGui.QApplication.translate("hotkey_edit", "standard hotkey", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyButton.setText(QtGui.QApplication.translate("hotkey_edit", "Win+G", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyEnabled.setText(QtGui.QApplication.translate("hotkey_edit", "enabled by default", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyDisablable.setText(QtGui.QApplication.translate("hotkey_edit", "can be disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyChangable.setText(QtGui.QApplication.translate("hotkey_edit", "can be changed", None, QtGui.QApplication.UnicodeUTF8))
        self.hotkeyMultiple.setText(QtGui.QApplication.translate("hotkey_edit", "allow multiple", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeLabel.setText(QtGui.QApplication.translate("hotkey_edit", "scope", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEverywhere.setText(QtGui.QApplication.translate("hotkey_edit", "everywhere", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeEnableIn.setText(QtGui.QApplication.translate("hotkey_edit", "only in:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeDisableIn.setText(QtGui.QApplication.translate("hotkey_edit", "everywhere but:", None, QtGui.QApplication.UnicodeUTF8))
        self.scopeChangable.setText(QtGui.QApplication.translate("hotkey_edit", "can be changed", None, QtGui.QApplication.UnicodeUTF8))

