# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eRiC\io\code\a2\ui\scopeDialog.ui'
#
# Created: Sat Sep  5 21:26:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScopeDialog(object):
    def setupUi(self, ScopeDialog):
        ScopeDialog.setObjectName("ScopeDialog")
        ScopeDialog.resize(1091, 324)
        self.verticalLayout = QtGui.QVBoxLayout(ScopeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.helpButton = QtGui.QPushButton(ScopeDialog)
        self.helpButton.setMinimumSize(QtCore.QSize(200, 0))
        self.helpButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.helpButton.setStyleSheet("* {text-align: right}")
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_5.addWidget(self.helpButton)
        self.scopeText = QtGui.QLineEdit(ScopeDialog)
        self.scopeText.setReadOnly(True)
        self.scopeText.setObjectName("scopeText")
        self.horizontalLayout_5.addWidget(self.scopeText)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleButton = QtGui.QPushButton(ScopeDialog)
        self.titleButton.setMinimumSize(QtCore.QSize(200, 0))
        self.titleButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.titleButton.setStyleSheet("* {text-align: right}")
        self.titleButton.setObjectName("titleButton")
        self.horizontalLayout_2.addWidget(self.titleButton)
        self.scopeTitle = QtGui.QLineEdit(ScopeDialog)
        self.scopeTitle.setObjectName("scopeTitle")
        self.horizontalLayout_2.addWidget(self.scopeTitle)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.classButton = QtGui.QPushButton(ScopeDialog)
        self.classButton.setMinimumSize(QtCore.QSize(200, 0))
        self.classButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.classButton.setStyleSheet("* {text-align: right}")
        self.classButton.setObjectName("classButton")
        self.horizontalLayout_3.addWidget(self.classButton)
        self.scopeClass = QtGui.QLineEdit(ScopeDialog)
        self.scopeClass.setObjectName("scopeClass")
        self.horizontalLayout_3.addWidget(self.scopeClass)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exeButton = QtGui.QPushButton(ScopeDialog)
        self.exeButton.setMinimumSize(QtCore.QSize(200, 0))
        self.exeButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.exeButton.setStyleSheet("* {text-align: right}")
        self.exeButton.setObjectName("exeButton")
        self.horizontalLayout_4.addWidget(self.exeButton)
        self.scopeExe = QtGui.QLineEdit(ScopeDialog)
        self.scopeExe.setObjectName("scopeExe")
        self.horizontalLayout_4.addWidget(self.scopeExe)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtGui.QPushButton(ScopeDialog)
        self.okButton.setStyleSheet("* {background-color: #43B6FF;}")
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(ScopeDialog)
        self.cancelButton.setFlat(True)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ScopeDialog)
        QtCore.QMetaObject.connectSlotsByName(ScopeDialog)

    def retranslateUi(self, ScopeDialog):
        ScopeDialog.setWindowTitle(QtGui.QApplication.translate("ScopeDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("ScopeDialog", "scope description", None, QtGui.QApplication.UnicodeUTF8))
        self.titleButton.setText(QtGui.QApplication.translate("ScopeDialog", "title", None, QtGui.QApplication.UnicodeUTF8))
        self.classButton.setText(QtGui.QApplication.translate("ScopeDialog", "window class", None, QtGui.QApplication.UnicodeUTF8))
        self.exeButton.setText(QtGui.QApplication.translate("ScopeDialog", "executable", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("ScopeDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ScopeDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

