# -*- coding: utf-8 -*-

"""
Form generated from reading UI file 'cursor_block.ui'

Created by: Qt User Interface Compiler version 6.4.2

WARNING! All changes made in this file will be lost when recompiling UI file!
"""

from a2qt.QtWidgets import QGridLayout, QHBoxLayout, QPushButton, QVBoxLayout, QWidget
from a2qt.QtGui import QFont
from a2qt.QtCore import QMetaObject

class Ui_CursorBlock:
    def setupUi(self, CursorBlock):
        if not CursorBlock.objectName():
            CursorBlock.setObjectName('CursorBlock')
        self.verticalLayout = QVBoxLayout(CursorBlock)
        self.verticalLayout.setObjectName('verticalLayout')
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.print_block = QHBoxLayout()
        self.print_block.setObjectName('print_block')
        self.printscreen = QPushButton(CursorBlock)
        self.printscreen.setObjectName('printscreen')
        self.printscreen.setText('Print\nScreen')
        self.print_block.addWidget(self.printscreen)
        self.scrolllock = QPushButton(CursorBlock)
        self.scrolllock.setObjectName('scrolllock')
        self.scrolllock.setText('Scroll\nLock')
        self.print_block.addWidget(self.scrolllock)
        self.pause = QPushButton(CursorBlock)
        self.pause.setObjectName('pause')
        self.pause.setText('Pause')
        self.print_block.addWidget(self.pause)
        self.print_spacer = QWidget(CursorBlock)
        self.print_spacer.setObjectName('print_spacer')
        self.print_block.addWidget(self.print_spacer)
        self.verticalLayout.addLayout(self.print_block)
        self.f_spacer = QWidget(CursorBlock)
        self.f_spacer.setObjectName('f_spacer')
        self.verticalLayout.addWidget(self.f_spacer)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.delete = QPushButton(CursorBlock)
        self.delete.setObjectName('delete')
        self.delete.setText('Del')
        self.gridLayout.addWidget(self.delete, 1, 0, 1, 1)
        self.end = QPushButton(CursorBlock)
        self.end.setObjectName('end')
        self.end.setText('End')
        self.gridLayout.addWidget(self.end, 1, 1, 1, 1)
        self.down = QPushButton(CursorBlock)
        self.down.setObjectName('down')
        font = QFont()
        font.setBold(True)
        self.down.setFont(font)
        self.down.setText('d')
        self.gridLayout.addWidget(self.down, 4, 1, 1, 1)
        self.insert = QPushButton(CursorBlock)
        self.insert.setObjectName('insert')
        self.insert.setText('Insert')
        self.gridLayout.addWidget(self.insert, 0, 0, 1, 1)
        self.pgup = QPushButton(CursorBlock)
        self.pgup.setObjectName('pgup')
        self.pgup.setText('Page\nUp')
        self.gridLayout.addWidget(self.pgup, 0, 2, 1, 1)
        self.left = QPushButton(CursorBlock)
        self.left.setObjectName('left')
        self.left.setFont(font)
        self.left.setText('l')
        self.gridLayout.addWidget(self.left, 4, 0, 1, 1)
        self.home = QPushButton(CursorBlock)
        self.home.setObjectName('home')
        self.home.setText('Home')
        self.gridLayout.addWidget(self.home, 0, 1, 1, 1)
        self.up = QPushButton(CursorBlock)
        self.up.setObjectName('up')
        self.up.setFont(font)
        self.up.setText('u')
        self.gridLayout.addWidget(self.up, 3, 1, 1, 1)
        self.pgdn = QPushButton(CursorBlock)
        self.pgdn.setObjectName('pgdn')
        self.pgdn.setText('Page\nDown')
        self.gridLayout.addWidget(self.pgdn, 1, 2, 1, 1)
        self.right = QPushButton(CursorBlock)
        self.right.setObjectName('right')
        self.right.setFont(font)
        self.right.setText('r')
        self.gridLayout.addWidget(self.right, 4, 2, 1, 1)
        self.f_spacer_2 = QWidget(CursorBlock)
        self.f_spacer_2.setObjectName('f_spacer_2')
        self.gridLayout.addWidget(self.f_spacer_2, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(1, 1)
        QMetaObject.connectSlotsByName(CursorBlock)
