# -*- coding: utf-8 -*-

"""
Form generated from reading UI file 'mouse.ui'

Created by: Qt User Interface Compiler version 6.4.2

WARNING! All changes made in this file will be lost when recompiling UI file!
"""

from a2qt.QtWidgets import QHBoxLayout, QPushButton, QSizePolicy, QVBoxLayout, QWidget
from a2qt.QtCore import QMetaObject, QSize, Qt

class Ui_Mouse:
    def setupUi(self, Mouse):
        if not Mouse.objectName():
            Mouse.setObjectName('Mouse')
        Mouse.setWindowTitle('Form')
        self.verticalLayout = QVBoxLayout(Mouse)
        self.verticalLayout.setObjectName('verticalLayout')
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.inner_widget = QWidget(Mouse)
        self.inner_widget.setObjectName('inner_widget')
        self.inner_widget.setMaximumSize(QSize(420, 200))
        self.main_layout = QHBoxLayout(self.inner_widget)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName('main_layout')
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.lbutton = QPushButton(self.inner_widget)
        self.lbutton.setObjectName('lbutton')
        self.lbutton.setMinimumSize(QSize(0, 200))
        self.lbutton.setMaximumSize(QSize(100, 200))
        self.lbutton.setBaseSize(QSize(0, 0))
        self.lbutton.setToolTip('Left Mouse Button')
        self.lbutton.setText('L')
        self.main_layout.addWidget(self.lbutton)
        self.wheelleft = QPushButton(self.inner_widget)
        self.wheelleft.setObjectName('wheelleft')
        self.wheelleft.setMaximumSize(QSize(40, 180))
        self.wheelleft.setToolTip('Wheel Left')
        self.main_layout.addWidget(self.wheelleft)
        self.middle_layout = QVBoxLayout()
        self.middle_layout.setSpacing(10)
        self.middle_layout.setObjectName('middle_layout')
        self.wheelup = QPushButton(self.inner_widget)
        self.wheelup.setObjectName('wheelup')
        self.wheelup.setMaximumSize(QSize(100, 40))
        self.wheelup.setToolTip('Wheel Up')
        self.middle_layout.addWidget(self.wheelup, 0, Qt.AlignTop)
        self.mbutton = QPushButton(self.inner_widget)
        self.mbutton.setObjectName('mbutton')
        self.mbutton.setMinimumSize(QSize(0, 100))
        self.mbutton.setMaximumSize(QSize(100, 16777215))
        self.mbutton.setToolTip('Middle Mouse Button')
        self.mbutton.setText('M')
        self.middle_layout.addWidget(self.mbutton, 0, Qt.AlignVCenter)
        self.wheeldown = QPushButton(self.inner_widget)
        self.wheeldown.setObjectName('wheeldown')
        self.wheeldown.setMaximumSize(QSize(100, 40))
        self.wheeldown.setToolTip('Wheel Down')
        self.middle_layout.addWidget(self.wheeldown, 0, Qt.AlignBottom)
        self.main_layout.addLayout(self.middle_layout)
        self.wheelright = QPushButton(self.inner_widget)
        self.wheelright.setObjectName('wheelright')
        self.wheelright.setMaximumSize(QSize(40, 180))
        self.wheelright.setToolTip('Wheel Right')
        self.main_layout.addWidget(self.wheelright)
        self.rbutton = QPushButton(self.inner_widget)
        self.rbutton.setObjectName('rbutton')
        self.rbutton.setMinimumSize(QSize(0, 200))
        self.rbutton.setMaximumSize(QSize(100, 200))
        self.rbutton.setToolTip('Right Mouse Button')
        self.rbutton.setText('R')
        self.main_layout.addWidget(self.rbutton)
        self.verticalLayout.addWidget(self.inner_widget)
        self._mouse_body = QPushButton(Mouse)
        self._mouse_body.setObjectName('_mouse_body')
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._mouse_body.sizePolicy().hasHeightForWidth())
        self._mouse_body.setSizePolicy(sizePolicy)
        self.verticalLayout.addWidget(self._mouse_body)
        self.verticalLayout.setStretch(1, 1)
        QMetaObject.connectSlotsByName(Mouse)
